export const PLATFORM_STRUCTURED_EXERCISES_COUNT = 1236
export const PLATFORM_STRUCTURED_EXERCISES_LABEL = '1.200+'
export const PLATFORM_STRUCTURED_EXERCISES_TEXT = 'Ejercicios reales'
export const PLATFORM_STRUCTURED_EXERCISES_LONG_TEXT = 'Ejercicios reales PAU'
