-- Redacta las 18 lecciones de Curso de Historia de la Filosofía (13 autores + 5
-- problemas transversales), en curriculum_content_v2 — hoy 0 filas para este subject
-- (solo existía el catálogo en curriculum_topics, creado en una tarea anterior).
--
-- Contenido 100% original, redactado con palabras propias a partir de qué aspectos de
-- cada autor entran realmente en el examen de Madrid (contrastado contra los textos
-- reales de app/data/historia_filosofia_madrid.ts) — no se copia ningún fragmento largo
-- de esos textos ni de ningún manual/Wikipedia; los "fragmentos típicos" de los ejemplos
-- son paráfrasis breves construidas para ilustrar el TIPO de argumento, no citas
-- literales de examen.
--
-- Los autores con un único ejercicio real en el banco (Agustín de Hipona, Hannah
-- Arendt) reciben lecciones igual de completas que el resto, con su propio aviso
-- recordando que "poco frecuente" no es "poco probable".
--
-- Las 5 lecciones de problema transversal explican el problema en sí y contrastan
-- explícitamente entre los autores reales del temario que lo abordan, dando al alumno
-- un criterio para elegir con qué autor responder — no son una definición de diccionario.
--
-- topic_id ya poblado desde el insert, enlazando con los 18 topics creados en la tarea
-- anterior. review_status='draft' — no publicadas todavía. Historia de la Filosofía
-- sigue fuera de PRIVATE_BETA_SUBJECTS/ALLOWED_GENERATE_SUBJECTS.

INSERT INTO curriculum_content_v2 (subject, block_key, block_slug, sort_order, title, concept_markdown, worked_example_markdown, practice_prompt, alert_markdown, topic_id, review_status) VALUES
  ('historia_filosofia', 'Autores', 'autores', 1, 'Descartes', $mkd$En el examen, los textos de Descartes vienen casi siempre de las *Meditaciones metafísicas* y giran en torno al **método de la duda** y al **cogito**. Descartes decide dudar de todo lo que pueda ser puesto en duda —los sentidos engañan a veces, y hasta las verdades matemáticas podrían ser falsas si existiera un genio maligno que nos engañara— para encontrar algo que resista cualquier duda posible.

Lo único que sobrevive a la duda es que, mientras dudo, **pienso**, y mientras pienso, **existo**: de ahí el "pienso, luego existo". A partir de esta certeza, Descartes reconstruye el conocimiento clasificando las ideas en tres tipos —**innatas** (nacen con la mente, como la idea de Dios o de sustancia), **adventicias** (parecen venir de fuera, como la idea del sol que percibo) y **facticias** (inventadas por mí, como una sirena)— y usa la idea de un ser infinito y perfecto que tengo en mí para demostrar que Dios existe: un ser finito e imperfecto como yo no podría haber producido por sí solo la idea de algo infinito y perfecto.

En el comentario de texto, lo habitual es que el fragmento se centre en UNO de estos tres momentos —la duda y el cogito, la clasificación de las ideas, o la prueba de la existencia de Dios— y hay que identificar cuál de los tres es, porque cada uno responde a una pregunta distinta.$mkd$, $mkd$Fragmento típico: "...advierto que, si dudo, pienso, y que mientras pienso soy algo; y aunque todo lo demás fuese engañoso, esta verdad no podría serlo."

Identificación: este fragmento pertenece al momento de la **duda metódica y el cogito** (no a la clasificación de ideas ni a la prueba de Dios), porque el argumento es exactamente "dudar → pensar → existir". En el comentario hay que explicar que la duda no es un fin en sí misma sino una herramienta: sirve para encontrar una primera verdad indudable sobre la que reconstruir el resto del conocimiento.$mkd$, $mkd$Un fragmento dice: "Si juzgo que la idea del sol viene de fuera de mí, hallo razones que me inclinan a creerlo, pero razones que no son del todo demostrativas." ¿A cuál de los tres momentos del pensamiento de Descartes corresponde — la duda y el cogito, la clasificación de las ideas, o la prueba de la existencia de Dios? Justifica tu respuesta.$mkd$, $mkd$⚠️ No confundas la duda metódica de Descartes con un escepticismo real: Descartes no cree que todo sea falso, solo lo pone en duda temporalmente como estrategia para hallar una certeza absoluta.$mkd$, '9a8390fc-5671-40fb-91c6-cc3caa79e575'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 2, 'Tomás de Aquino', $mkd$Los textos de Tomás de Aquino en el examen vienen de la *Suma Teológica* y casi siempre presentan una de las **cinco vías** con las que demuestra racionalmente la existencia de Dios, partiendo de la observación del mundo sensible, nunca de una intuición directa. Las cinco vías comparten una misma estructura: se observa un hecho del mundo, se argumenta que la cadena de ese hecho no puede prolongarse hasta el infinito, y se concluye que tiene que haber un primer término que explique la serie sin ser él mismo parte de ella — a ese primer término lo llama Dios.

Conviene distinguirlas bien: **1ª vía** (del movimiento: todo lo que se mueve es movido por otro, tiene que haber un primer motor inmóvil); **2ª vía** (de la causa eficiente: nada es causa de sí mismo, tiene que haber una primera causa incausada); **3ª vía** (de la contingencia: todo lo que existe podría no existir, tiene que haber algo necesario); **4ª vía** (de los grados de perfección: si hay cosas más o menos buenas/verdaderas, tiene que haber un máximo del que las demás participan); **5ª vía** (del orden: las cosas sin conocimiento actúan ordenadamente hacia un fin, así que alguien inteligente las dirige).

Un segundo tipo de texto, menos frecuente pero también real en el banco de exámenes, no presenta una vía sino que discute si la existencia de Dios es "evidente por sí misma" — Tomás de Aquino distingue entre lo evidente en sí mismo (donde el predicado ya está contenido en el sujeto) y lo evidente para nosotros, y argumenta que aunque la existencia de Dios sea evidente en sí misma, el ser humano necesita demostrarla partiendo de sus efectos.$mkd$, $mkd$Fragmento típico: "Vemos que las cosas naturales, careciendo de conocimiento, obran por un fin... luego existe un ser inteligente que dirige todas las cosas naturales a su fin."

Identificación: es la **quinta vía** (del orden o finalidad) — el argumento parte de que las cosas sin conocimiento actúan siempre o casi siempre del mismo modo para lograr lo mejor, lo cual solo se explica si algo inteligente las dirige, igual que una flecha solo llega a su blanco si alguien la dirige.$mkd$, $mkd$Un fragmento dice: "Nada puede pasar de la potencia al acto sino por algo que ya esté en acto... luego es necesario llegar a un primer motor que no sea movido por ningún otro." ¿A cuál de las cinco vías corresponde? Explica en 3-4 líneas la estructura del argumento.$mkd$, $mkd$⚠️ Las cinco vías no son intercambiables: aunque todas terminen concluyendo la existencia de Dios, cada una parte de una observación distinta del mundo — identificar bien de cuál se trata es el primer paso del comentario.$mkd$, 'b9292860-3c3a-494c-a362-462f9c82959b'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 3, 'Platón', $mkd$Los textos de Platón en el examen vienen del *Fedón* y giran en torno a dos ideas profundamente conectadas: la **teoría de la reminiscencia** y el **dualismo entre alma y cuerpo**.

La teoría de la reminiscencia sostiene que conocer no es aprender algo nuevo, sino **recordar** algo que el alma ya conocía antes de unirse al cuerpo — por ejemplo, cuando decimos que dos palos son "iguales", aplicamos una idea de igualdad perfecta que nunca hemos visto realizada en el mundo sensible, así que esa idea tuvo que ser adquirida por el alma en un momento anterior al nacimiento, en contacto directo con las Ideas.

Esta teoría solo tiene sentido si el alma existe antes del cuerpo y es de naturaleza distinta a él: de ahí el dualismo. El cuerpo, ligado a los sentidos, ofrece un conocimiento confuso y cambiante de las cosas sensibles; el alma, cuando se libera de la influencia del cuerpo y razona por sí misma, puede acceder a las Ideas eternas e inmutables. Por eso Platón describe el cuerpo casi como un obstáculo para el alma, y la filosofía como un entrenamiento para "separarse" de él ya en vida.$mkd$, $mkd$Fragmento típico: "Cuando el alma investiga por sí misma, se dirige a lo puro, eterno e inmortal... y esto es lo que llamamos sabiduría."

Identificación: este fragmento corresponde al **dualismo alma-cuerpo**, no a la reminiscencia — el argumento contrasta lo que ocurre cuando el alma actúa "por sí misma" (razón pura, accede a lo eterno) frente a cuando actúa "a través del cuerpo" (sentidos, mundo cambiante).$mkd$, $mkd$Un fragmento dice: "Si antes de nacer ya teníamos ese conocimiento y lo perdimos al nacer, y luego, usando los sentidos, lo recuperamos, ¿no es esto lo que llamamos aprender?" ¿A qué idea corresponde — la reminiscencia o el dualismo alma-cuerpo? Explica por qué.$mkd$, NULL, 'c612c3ad-447a-4500-9a0e-0d77f7e4694c'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 4, 'Kant', $mkd$Los textos de Kant en el examen vienen de la *Crítica de la razón pura* y se centran en su pregunta central: ¿cómo es posible el conocimiento científico, y hasta dónde puede llegar la razón sin perderse en especulaciones vacías?

Para responder, Kant cruza dos parejas de conceptos: por un lado, **juicios analíticos** (el predicado ya está contenido en el sujeto, no añaden información nueva, como "todo cuerpo es extenso") frente a **juicios sintéticos** (el predicado añade algo que no estaba en el sujeto, como "este cuerpo pesa dos kilos"); por otro, **a priori** (independiente de la experiencia, universal y necesario) frente a **a posteriori** (depende de la experiencia, contingente). La ciencia, para Kant, se apoya en juicios **sintéticos a priori** — añaden información nueva pero son universales y necesarios, como las proposiciones matemáticas o el principio de causalidad.

Cuando el texto habla de la posibilidad de la metafísica, Kant advierte de que la razón tiende a usar estos mismos conceptos (causa, sustancia) más allá de toda experiencia posible —para hablar de Dios, el alma o el universo como totalidad— y ahí es donde el conocimiento deja de ser seguro: la metafísica tradicional pretende un conocimiento sintético a priori que, para Kant, no está justificado de la misma manera que en las matemáticas o la física.$mkd$, $mkd$Fragmento típico: "Todo cuerpo es extenso es una proposición a priori porque el concepto de extensión ya está en el concepto de cuerpo; pero este cuerpo pesa dos kilos es un juicio sintético, porque el peso no está contenido en el concepto de cuerpo."

Identificación: corresponde a la distinción **analítico/sintético**, no a la de a priori/a posteriori — el criterio que se usa es si el predicado "añade" algo al concepto del sujeto, que es justamente el criterio analítico/sintético.$mkd$, $mkd$Un fragmento afirma que ciertos conocimientos abandonan "el campo de toda experiencia posible" y pretenden extender nuestros juicios más allá de sus límites mediante conceptos a los que no corresponde ningún objeto empírico. ¿A qué problema kantiano corresponde? Explica su relación con los juicios sintéticos a priori.$mkd$, $mkd$⚠️ No basta con decir "esto es a priori porque no viene de la experiencia" — hay que precisar también si el juicio es analítico o sintético, porque son dos ejes distintos y el examen suele premiar que se distingan con claridad.$mkd$, 'e7b6c9a8-5eae-4383-ae6a-f39d7d0a66ce'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 5, 'Rousseau', $mkd$Los textos de Rousseau en el examen vienen de *Del contrato social* y explican cómo los seres humanos, en algún momento, dejan de poder sobrevivir aislados en el estado de naturaleza y necesitan unir sus fuerzas sin perder su libertad — ese es el problema que el **contrato social** viene a resolver.

La solución de Rousseau es que cada persona se entregue **por entero** a la comunidad, sin reservarse nada para sí ni someterse a ningún otro individuo en particular: como todos se dan de la misma manera, nadie tiene interés en hacer la condición más pesada para los demás. De esa unión nace un cuerpo colectivo que Rousseau llama **voluntad general** — no es la suma de las voluntades particulares (eso sería la "voluntad de todos"), sino lo que resulta cuando cada persona piensa en el bien común y no solo en su interés privado.

Un punto que suele aparecer en el comentario es que quien no obedezca la voluntad general "será obligado a ello por todo el cuerpo", lo que Rousseau resume en la paradójica expresión de que se le "forzará a ser libre": la idea es que la verdadera libertad no consiste en hacer lo que a cada uno le apetezca en cada momento, sino en obedecer una ley que uno mismo, como parte del cuerpo político, ha contribuido a crear.$mkd$, $mkd$Fragmento típico: "Cada uno de nosotros pone en común su persona y todo su poder bajo la suprema dirección de la voluntad general, y recibimos a cada miembro como parte indivisible del todo."

Identificación: corresponde al momento de la **formación del pacto social** — hay que explicar la enajenación total (cada uno se entrega por entero) y el resultado (un cuerpo colectivo regido por la voluntad general), distinguiendo esto del razonamiento sobre por qué el pacto puede llegar a ser coactivo ("forzar a ser libre"), que es un momento posterior.$mkd$, $mkd$Un fragmento dice que cada individuo puede tener, como hombre, una voluntad particular distinta de la que tiene como ciudadano, y que su interés privado puede hablarle de forma distinta al interés común. ¿Qué tensión del contractualismo de Rousseau ilustra esto? Relaciónalo con el concepto de voluntad general.$mkd$, NULL, '7d8503da-da5b-4803-9b62-1a03f9e1415b'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 6, 'Hume', $mkd$Los textos de Hume en el examen vienen de la *Investigación sobre el entendimiento humano* y giran siempre en torno a su crítica al concepto de **causalidad**. La pregunta es: cuando decimos que A causa B, ¿qué es exactamente lo que percibimos?

Hume observa que lo único que los sentidos nos ofrecen es que B sigue siempre a A (una **conjunción constante** en el tiempo), pero nunca percibimos ningún "vínculo" o "poder" entre ambos que explique por qué A tiene que producir B — no hay ninguna impresión sensible de la "conexión necesaria" misma, solo de una cosa seguida de otra. Su ejemplo típico es el choque de dos bolas de billar: vemos que una golpea a la otra y esta se mueve, pero no vemos ningún "poder" que pase de una bola a la otra, solo la sucesión de los dos hechos.

Entonces, ¿de dónde viene nuestra firme creencia en que A causa B? Para Hume no viene de la razón (que no podría demostrar por qué el futuro tiene que repetir el pasado), sino del **hábito o costumbre**: tras observar muchas veces la misma sucesión, la mente queda acostumbrada a esperar B en cuanto aparece A, y esa expectativa psicológica es lo que llamamos "necesidad" causal — una creencia justificada por la práctica, no un conocimiento racional demostrado.$mkd$, $mkd$Fragmento típico: "Tras la repetición de casos similares, la mente es conducida por el hábito a esperar, al aparecer un suceso, su acompañante usual."

Identificación: es el momento central de la crítica humeana — hay que explicar que la "conexión necesaria" no está en los objetos ni se percibe por los sentidos, sino que es un hábito mental generado por la repetición, distinguiéndolo de la mera constatación inicial de que "solo vemos sucesión, no conexión".$mkd$, $mkd$Un fragmento afirma que, aunque hayamos observado muchas veces que un acontecimiento sigue a otro, no tenemos derecho a enunciar una regla general sobre el futuro basándonos solo en esa experiencia pasada. ¿Qué problema plantea sobre el conocimiento causal? Relaciónalo con la noción de costumbre.$mkd$, $mkd$⚠️ Cuidado con confundir "costumbre" con "error": para Hume la creencia causal no es racionalmente demostrable, pero sí es psicológicamente inevitable y útil para la vida — no está diciendo que la causalidad no exista, sino que no podemos fundamentarla en la razón pura.$mkd$, '58226462-4d35-4044-b008-85b00cdb93d3'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 7, 'Habermas', $mkd$Los textos de Habermas en el examen vienen de *Tres modelos normativos de democracia* y presentan su comparación entre tres formas de entender la democracia, para terminar defendiendo la suya propia.

El modelo **liberal** entiende la política como un mercado en el que individuos con intereses privados compiten y negocian, y el Estado se limita a arbitrar ese proceso. El modelo **republicano** entiende la democracia como autoorganización política de una comunidad ética que se reconoce a sí misma como un todo mediante la participación de sus ciudadanos — aquí la sociedad se centra en el Estado, no al revés. Habermas no se queda con ninguno de los dos: propone un tercer modelo, la **política deliberativa**, en el que las decisiones legítimas no surgen ni de la negociación de intereses privados (liberal) ni de una identidad ética ya dada (republicano), sino de procesos de comunicación y argumentación pública en condiciones adecuadas.

Para Habermas, lo decisivo es que existan **condiciones de comunicación** suficientemente institucionalizadas —espacios donde los ciudadanos puedan deliberar en igualdad de condiciones— para que la formación de la opinión y la voluntad colectivas tenga fuerza legitimadora. La legitimidad democrática, en su modelo, depende de la **calidad del proceso deliberativo**, no de quién gana una negociación de intereses ni de una supuesta identidad compartida de antemano.$mkd$, $mkd$Fragmento típico: "La democracia equivale a la autoorganización política de la sociedad... la comunidad se torna consciente de sí misma mediante la voluntad colectiva de los ciudadanos."

Identificación: describe el modelo **republicano**, no el deliberativo propio de Habermas — la clave es que la sociedad "se centra en el Estado" y se entiende como una comunidad ética ya constituida, frente al modelo deliberativo, donde la legitimidad depende del proceso comunicativo entre ciudadanos con intereses y valores plurales.$mkd$, $mkd$Un fragmento describe la política como un proceso en el que individuos con intereses privados negocian y el Estado se limita a garantizar las reglas del juego. ¿A cuál de los tres modelos de Habermas corresponde? Compáralo brevemente con el modelo deliberativo que Habermas defiende.$mkd$, NULL, '2ba8433d-dfad-4afb-9dcb-1f1ac1539a5b'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 8, 'Ortega y Gasset', $mkd$Los textos de Ortega y Gasset en el examen vienen de *El tema de nuestro tiempo* y desarrollan su teoría del **perspectivismo**: la idea de que todo conocimiento de la realidad se produce desde un punto de vista concreto, y que eso no es un defecto del conocimiento sino su condición.

Ortega parte de una imagen sencilla: dos personas mirando el mismo paisaje desde lugares distintos no ven exactamente lo mismo, pero eso no significa que uno de los dos paisajes sea "falso" — ambos son reales, porque la realidad, como un paisaje, tiene **infinitas perspectivas** igualmente verdaderas, y ninguna por separado agota la realidad entera. Lo que sería falso es pretender que la propia perspectiva es la única válida, ignorando que es solo una entre muchas posibles.

Con esto, Ortega se opone a dos posturas: al **relativismo**, que diría que como cada uno ve algo distinto no hay verdad objetiva (para Ortega sí la hay, pero se construye sumando perspectivas, no eliminándolas); y al **racionalismo abstracto**, que buscaría un "punto de vista absoluto" desde el que ver la realidad sin ningún punto de vista particular, algo que para Ortega es una ficción imposible: todo conocimiento humano es, por naturaleza, conocimiento desde algún lugar.$mkd$, $mkd$Fragmento típico: "El punto de vista absoluto y ubicuo no existe propiamente: es un punto de vista ficticio y abstracto... desde él no se ve lo real."

Identificación: es la crítica de Ortega al **racionalismo abstracto** (el ideal de un conocimiento sin perspectiva), no una defensa del relativismo — hay que aclarar que Ortega no niega que exista una verdad, solo niega que se pueda acceder a ella eliminando todo punto de vista particular.$mkd$, $mkd$Un fragmento dice que la divergencia entre lo que ven dos sujetos distintos no implica que uno de ellos esté equivocado, porque cada cual ve una realidad y no una ficción. ¿Qué tesis del perspectivismo orteguiano ilustra esto? Relaciónalo con la crítica al racionalismo abstracto.$mkd$, NULL, '336dee00-0f31-4472-9de9-913323041085'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 9, 'Marx', $mkd$Los textos de Marx en el examen vienen de *La ideología alemana* y pueden tratar tres cuestiones distintas, así que lo primero es identificar cuál de ellas plantea el fragmento.

La primera es la **conciencia como producto social**: Marx rechaza que la conciencia sea algo "puro" o independiente de la vida material — nace ligada al lenguaje, y el lenguaje nace de la necesidad de relacionarse con otros seres humanos, así que la conciencia es, desde el principio, un producto social. La segunda es el **Estado y la lucha de clases**: las luchas políticas dentro del Estado son, según Marx, la forma "ilusoria" en que se expresan las luchas reales entre clases sociales — quien controla la producción tiende a presentar su interés de clase como si fuera el interés general de toda la sociedad. La tercera es el **comunismo como movimiento histórico real**: Marx insiste en que el comunismo no es un ideal abstracto al que la realidad deba ajustarse, sino el movimiento efectivo que ya está transformando el "estado de cosas actual", surgido de condiciones materiales concretas.

Las tres ideas comparten el método de Marx, el **materialismo histórico**: explicar las ideas, las instituciones políticas y hasta la conciencia a partir de las condiciones materiales y económicas de una sociedad, y no al revés.$mkd$, $mkd$Fragmento típico: "Toda clase que aspire a implantar su dominación tiene que empezar conquistando el poder político, para poder presentar su interés como el interés general."

Identificación: corresponde al análisis del **Estado y la lucha de clases** — hay que explicar que, para Marx, las luchas políticas "visibles" esconden un conflicto de clases más profundo, y que el poder político sirve para universalizar ideológicamente un interés que en realidad es particular.$mkd$, $mkd$Un fragmento dice que el lenguaje es tan antiguo como la conciencia, y que la conciencia es desde el principio un producto social. ¿A cuál de los tres temas marxistas del examen corresponde? Explica por qué esto es coherente con el materialismo histórico.$mkd$, NULL, '94c95b5b-9ab5-44ab-bf91-0dae0249776a'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 10, 'Nietzsche', $mkd$Los textos de Nietzsche en el examen vienen de *La gaya ciencia* y suelen tratar una de estas tres cuestiones. La primera es la **crítica a la moral tradicional**: Nietzsche denuncia que, hasta ahora, nadie ha tratado la moral como un verdadero problema filosófico — al contrario, ha funcionado como un lugar de acuerdo pacífico donde los pensadores dejaban de discutir, en vez de someterla ella misma a examen crítico.

La segunda es la **muerte de Dios y el nihilismo**: Nietzsche anuncia que la creencia en el Dios cristiano ha dejado de ser creíble para la cultura europea, y que este acontecimiento va a proyectar "sombras" sobre toda la civilización — porque buena parte de los valores y certezas de Occidente dependían de esa creencia; al desaparecer, se abre el riesgo del **nihilismo** (la sensación de que nada tiene ya un valor firme).

La tercera es la **crítica a las convicciones en la ciencia**: Nietzsche sostiene que una convicción (una creencia sostenida con firmeza, casi como un dogma) no debería tener cabida en el conocimiento científico salvo que se rebaje a ser una simple hipótesis provisional sometida a prueba — la ciencia, para ser honesta, tiene que desconfiar de sus propias certezas, no aferrarse a ellas.$mkd$, $mkd$Fragmento típico: "El mayor acontecimiento reciente es que Dios ha muerto, y esto empieza ya a proyectar sus primeras sombras sobre Europa."

Identificación: corresponde a la **muerte de Dios y el nihilismo** — conviene explicar que "Dios ha muerto" no es un enunciado sobre biología o teología, sino sobre la pérdida de credibilidad cultural de la creencia cristiana, y anticipar las consecuencias (pérdida de certezas, riesgo de nihilismo) que Nietzsche desarrolla en el resto del texto.$mkd$, $mkd$Un fragmento se pregunta por qué nadie ha tratado la moral como un problema personal, digno de duda y examen, y afirma que hasta ahora era más bien "un lugar de acuerdo" entre los pensadores. ¿A cuál de los tres temas nietzscheanos corresponde? Explica con tus palabras qué le reprocha Nietzsche a la moral tradicional.$mkd$, NULL, '063406fc-042b-4d02-bb0d-bb929e633878'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 11, 'Aristóteles', $mkd$Los textos de Aristóteles en el examen vienen de la *Ética a Nicómaco* y tratan dos cuestiones relacionadas: qué es la **felicidad** (el fin último de la vida humana) y cómo se adquiere la **virtud**.

Sobre la felicidad, Aristóteles descarta que consista en el placer o la diversión —sería absurdo vivir y esforzarse toda la vida solo para divertirse, aunque reconoce que la diversión tiene su lugar como descanso necesario para poder dedicarse después a cosas serias—. Lo característico de la felicidad es que es el único fin que se busca **por sí mismo** y nunca como medio para otra cosa: todo lo demás (dinero, honores, placer) se desea en vista de algo más, pero la felicidad se desea solo por ella misma. Entre las actividades humanas, Aristóteles sitúa en el punto más alto la **actividad contemplativa** (el ejercicio de la razón teórica), porque no depende de fines externos ni de la agitación de la acción política o militar, y lleva consigo un placer propio.

Sobre la virtud, Aristóteles insiste en que no basta con conocer la teoría de lo que está bien: **nos volvemos justos haciendo actos justos**, igual que se aprende un oficio practicándolo — quien se refugia solo en la teoría, sin actuar, cree que filosofa pero en realidad no se hace mejor persona.$mkd$, $mkd$Fragmento típico: "Nadie podría llegar a ser bueno sin realizar acciones justas y moderadas; pero la mayoría de la gente, refugiándose en la teoría, cree filosofar y así poder ser buena."

Identificación: corresponde al tema de la **virtud como hábito práctico**, no a la definición de la felicidad — el argumento central es que la virtud se adquiere actuando, no solo conociendo la teoría moral, y hay que señalar la crítica implícita a quienes confunden "saber de ética" con "ser éticos".$mkd$, $mkd$Un fragmento afirma que la actividad del pensamiento contemplativo, al no perseguir ningún fin fuera de sí misma, es la que mejor encaja con la idea de una felicidad completa y autosuficiente. ¿A qué tema aristotélico corresponde? Relaciónalo con por qué Aristóteles descarta el placer o la diversión como la felicidad misma.$mkd$, NULL, '09531eee-fd59-49d8-bfbb-660e6f658c57'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 12, 'Agustín de Hipona', $mkd$El único texto de Agustín de Hipona presente en el banco de exámenes viene de *Del libre albedrío*, pero conviene prepararlo con el mismo cuidado que a los autores con más ejercicios, porque cualquier convocatoria puede incluirlo y su argumento tiene una estructura muy concreta que hay que dominar.

El problema de fondo es: si Dios es justo y castiga el pecado y premia las buenas acciones, ¿qué exige eso sobre la naturaleza humana? Agustín argumenta que el castigo y el premio solo tienen sentido si las acciones que se castigan o premian fueron hechas **libremente** — un acto que no se hace voluntariamente no puede llamarse propiamente ni pecado ni buena acción, porque falta la responsabilidad de quien actúa. Por tanto, si el ser humano no tuviera **libre albedrío** (voluntad libre para elegir entre el bien y el mal), sería injusto tanto castigarlo como premiarlo por sus actos.

El argumento tiene una estructura muy clara que conviene identificar en el comentario: parte de un hecho que se da por bueno (que existe la justicia divina, que premia y castiga) y de ahí **deduce** una condición necesaria para que ese hecho tenga sentido (que el ser humano sea libre). Es un argumento típico de la filosofía cristiana medieval: no se limita a describir la libertad humana, sino que la demuestra a partir de una verdad religiosa que se da por establecida.$mkd$, $mkd$Fragmento típico: "Si el ser humano no tuviera una voluntad libre, tanto el castigo como el premio serían injustos; pero ha tenido que haber justicia en ambos, luego el ser humano tiene libre albedrío."

Identificación: es el argumento central de Agustín sobre el **libre albedrío** — en el comentario conviene explicitar la forma del razonamiento (si no hay libertad, no hay justicia posible en el castigo/premio; hay justicia; luego hay libertad) y situarlo en su contexto: es una prueba teológica de una tesis antropológica.$mkd$, $mkd$Explica con tus propias palabras por qué, para Agustín de Hipona, sería "injusto" castigar o premiar a alguien si esa persona no tuviera libre albedrío. ¿Qué relación establece el texto entre justicia divina y libertad humana?$mkd$, $mkd$⚠️ Aunque solo haya un ejercicio de Agustín de Hipona en los exámenes disponibles, su argumento puede aparecer en cualquier convocatoria futura — no te lo saltes por parecer "poco probable".$mkd$, 'b5ac4e42-67ed-4fe9-9433-342640bd6e30'::uuid, 'draft'),
  ('historia_filosofia', 'Autores', 'autores', 13, 'Hannah Arendt', $mkd$El único texto de Hannah Arendt presente en el banco de exámenes viene de *La condición humana*, y al igual que con Agustín de Hipona conviene prepararlo con la misma solidez que a los autores más representados, porque puede aparecer en cualquier convocatoria.

Arendt analiza cómo la tradición filosófica occidental, desde la Antigüedad y reforzada después por el cristianismo, ha entendido siempre la **vita activa** (la vida dedicada a la acción, el trabajo y la participación en los asuntos humanos) como algo de valor **derivado y secundario**, cuyo sentido consistiría solo en servir a las necesidades de la **vita contemplativa** (la vida dedicada a la contemplación y el pensamiento, considerada la más elevada). El cristianismo, con su promesa de una vida contemplativa plena en el más allá, reforzó todavía más esta jerarquía: la acción en este mundo quedaría subordinada a la contemplación como preparación para una vida futura.

Arendt no se limita a describir esta jerarquía tradicional: la presenta como una decisión filosófica e histórica concreta, no como algo evidente por sí mismo, abriendo la puerta a preguntarse si la vida activa merece de verdad ese lugar secundario — una pregunta que desarrolla en el resto de *La condición humana*, aunque el fragmento de examen se limite a exponer cómo se formó esa jerarquía tradicional.$mkd$, $mkd$Fragmento típico: "La vita activa recibe su significado y su limitada dignidad de la vita contemplativa, a cuyas necesidades sirve; el cristianismo reforzó esta subordinación con su promesa de una vida futura dedicada a la contemplación."

Identificación: describe la **jerarquía tradicional entre vita activa y vita contemplativa** — en el comentario conviene explicar los dos términos y señalar el papel histórico que Arendt atribuye al cristianismo en consolidar esa jerarquía, sin perder de vista que Arendt la describe para después cuestionarla.$mkd$, $mkd$Explica con tus propias palabras qué significa que, según la tradición que describe Arendt, la vita activa tenga una dignidad "derivada" de la vita contemplativa. ¿Qué papel atribuye el texto al cristianismo en esta jerarquía?$mkd$, $mkd$⚠️ Solo hay un ejercicio de Hannah Arendt en el banco actual, pero su argumento es autocontenido y claro — no requiere menos preparación que autores con más ejercicios.$mkd$, '1ea54724-1faa-4134-a725-6f20257d8cf1'::uuid, 'draft'),
  ('historia_filosofia', 'Problemas Transversales', 'problemas-transversales', 14, 'Ética y/o Moral', $mkd$Cuando el examen pide "exponga el problema de la ética y/o moral en un autor o corriente filosófica", no hay un único autor obligatorio — el enunciado te deja elegir, así que lo primero es decidir con qué autor te sientes más seguro para desarrollar la respuesta con precisión.

En el temario de Madrid, la pregunta ética se puede abordar desde posturas muy distintas: **Aristóteles** entiende la ética como la búsqueda de la felicidad a través de la virtud, que se adquiere practicando buenas acciones, no solo conociendo la teoría moral. **Nietzsche**, en cambio, no propone una ética positiva sino una crítica radical a la moral tradicional: denuncia que la moral nunca ha sido tratada como un problema real, sino como un terreno de acuerdo cómodo donde se deja de pensar. Y **Agustín de Hipona** aborda la moral desde una perspectiva religiosa, vinculando la posibilidad del bien y del mal a la existencia del libre albedrío, condición necesaria para que el castigo y el premio divinos tengan sentido.

Para estructurar bien la respuesta: (1) presenta con precisión la tesis central del autor elegido, (2) explica el argumento con el que la sostiene, y (3) si el tiempo lo permite, señala brevemente en qué se diferencia de otra postura ética del temario — eso demuestra que entiendes el problema, no solo la opinión de un autor aislado.$mkd$, $mkd$Ejemplo de elección razonada: si el examen no da ninguna pista sobre un autor concreto, y te sientes más cómodo con la idea de que "ser bueno" se aprende actuando en vez de solo pensando, la opción más segura es desarrollar la ética de **Aristóteles** (felicidad como fin, virtud como hábito adquirido por la práctica) en vez de intentar reconstruir de memoria la crítica nietzscheana a la moral, que exige matizar bien qué es lo que se está criticando exactamente.$mkd$, $mkd$Elige uno de los tres autores del temario de Madrid que tratan el problema de la ética o la moral (Aristóteles, Nietzsche o Agustín de Hipona) y redacta en 8-10 líneas su postura central, explicando también con qué argumento la defiende.$mkd$, NULL, '7f438d55-027e-4cae-b92a-875054ca8b83'::uuid, 'draft'),
  ('historia_filosofia', 'Problemas Transversales', 'problemas-transversales', 15, 'Sociedad y/o Política', $mkd$La pregunta transversal sobre "sociedad y/o política" permite elegir entre varios autores del temario, y elegir bien depende de saber distinguir claramente sus posturas — si se mezclan sin querer, el comentario pierde precisión.

**Rousseau** aborda el problema desde el contractualismo: explica cómo y por qué los seres humanos pasan del estado de naturaleza a la sociedad civil mediante un pacto en el que cada uno se entrega por entero a la comunidad, dando lugar a una voluntad general que no es la suma de intereses privados sino la orientación al bien común. **Marx**, en cambio, analiza la sociedad y el Estado desde el materialismo histórico: las instituciones políticas y las luchas dentro del Estado son la expresión de conflictos de clase basados en las condiciones materiales de producción — el Estado no es neutral, sirve a quien controla los medios de producción. **Habermas**, por último, compara distintos modelos de democracia y defiende que la legitimidad política depende de la calidad de los procesos de comunicación pública entre los ciudadanos, no de una negociación de intereses privados ni de una identidad colectiva ya dada.

Para elegir con cuál desarrollar la respuesta, pregúntate qué tipo de argumento controlas mejor: si es la idea de un pacto fundacional y una voluntad colectiva, Rousseau; si es el análisis de la política como reflejo de intereses de clase, Marx; si es la comparación entre modelos de legitimidad democrática, Habermas.$mkd$, $mkd$Ejemplo de elección razonada: si el examen no da pistas y recuerdas con claridad la distinción entre voluntad particular y voluntad general, la opción más eficaz es Rousseau, porque su argumento tiene una estructura muy reconocible (estado de naturaleza → pacto → voluntad general) que es fácil de explicar de forma ordenada en el tiempo disponible.$mkd$, $mkd$Elige uno de los tres autores del temario que tratan el problema de la sociedad y la política (Rousseau, Marx o Habermas) y redacta en 8-10 líneas su tesis central, indicando también frente a qué otra postura política se podría contrastar.$mkd$, NULL, '53c8543d-190f-403e-875f-6ff7c9094690'::uuid, 'draft'),
  ('historia_filosofia', 'Problemas Transversales', 'problemas-transversales', 16, 'Ser Humano', $mkd$La pregunta sobre "el problema del ser humano" pide una reflexión sobre qué es el ser humano o qué lo define, y el temario de Madrid ofrece varias respuestas muy distintas entre sí, así que conviene tener claro el enfoque de cada autor antes de elegir.

**Platón** define al ser humano a partir del dualismo entre alma y cuerpo: lo propiamente humano es el alma, mientras que el cuerpo, ligado a los sentidos, es más bien un obstáculo del que el alma debe liberarse para conocer de verdad. **Marx**, en cambio, entiende al ser humano como un ser esencialmente **social**: incluso algo tan interior como la conciencia nace ligada al lenguaje y a la necesidad de relacionarse con otros — no hay "naturaleza humana" al margen de las relaciones sociales y materiales en las que cada persona vive. **Hannah Arendt** aborda el problema desde la actividad: analiza cómo la tradición ha jerarquizado dos formas de vida humana, la vita activa y la vita contemplativa, subordinando siempre la primera a la segunda. Y **Agustín de Hipona** sitúa lo definitorio del ser humano en el **libre albedrío**, la capacidad de elegir libremente entre el bien y el mal.

Para elegir bien: si el enfoque que dominas es el de una parte "superior" (alma, razón) frente a una "inferior" (cuerpo, sentidos), Platón encaja mejor; si es la idea de que no existimos al margen de la sociedad, Marx; si es la comparación entre formas de vida, Arendt; si es la libertad como rasgo definitorio, Agustín.$mkd$, $mkd$Ejemplo de elección razonada: si el examen no aporta ninguna pista y controlas bien la teoría de la reminiscencia, tiene sentido desarrollar a Platón, porque el dualismo alma-cuerpo se explica de forma muy visual (el alma arrastrada por el cuerpo hacia lo cambiante, o liberada hacia lo eterno) y resulta fácil de estructurar en pocos minutos.$mkd$, $mkd$Elige uno de los cuatro autores del temario que tratan el problema del ser humano (Platón, Marx, Hannah Arendt o Agustín de Hipona) y redacta en 8-10 líneas cómo define ese autor lo propiamente humano.$mkd$, NULL, 'dbf9c3b3-a98a-49ff-b4eb-c90feb5ef3c8'::uuid, 'draft'),
  ('historia_filosofia', 'Problemas Transversales', 'problemas-transversales', 17, 'Dios', $mkd$La pregunta sobre "el problema de Dios" agrupa en el temario de Madrid tres posturas radicalmente distintas: dos que argumentan a favor de la existencia de Dios por caminos diferentes, y una que anuncia su pérdida de sentido cultural — conviene no confundirlas entre sí.

**Descartes** prueba la existencia de Dios desde dentro de la propia mente: parte de que tiene en sí la idea de un ser infinito y perfecto, y argumenta que un ser finito e imperfecto como él no podría haber producido por sí mismo esa idea — tiene que haber sido puesta en él por un ser realmente infinito, es decir, Dios. **Tomás de Aquino**, en cambio, parte de la observación del mundo sensible: sus cinco vías arrancan de hechos como el movimiento, la causalidad, la contingencia, los grados de perfección o el orden finalista de las cosas, y concluyen que tiene que existir un primer término que explique esa cadena sin depender de nada anterior. **Nietzsche**, por último, no discute pruebas racionales de la existencia de Dios: anuncia que la creencia cristiana en Dios ha perdido credibilidad cultural, lo cual no es un argumento sobre si Dios existe, sino un diagnóstico sobre las consecuencias de esa pérdida de fe para los valores de la civilización europea (el riesgo del nihilismo).

Para elegir con cuál desarrollar la respuesta: si controlas bien el argumento de la idea de infinito, Descartes; si prefieres un argumento basado en la observación del mundo, Tomás de Aquino; si el enfoque que mejor dominas es crítico y cultural, Nietzsche — pero en ese caso hay que dejar claro que Nietzsche no está "demostrando" que Dios no existe, sino describiendo el efecto de que ya no se crea en él.$mkd$, $mkd$Ejemplo de elección razonada: si recuerdas con seguridad las cinco vías y su estructura común (observación del mundo → imposibilidad de una serie infinita → primer término), Tomás de Aquino es la opción más segura, porque el argumento se puede reproducir de forma muy ordenada aunque no recuerdes el fragmento exacto del examen.$mkd$, $mkd$Elige uno de los tres autores del temario que tratan el problema de Dios (Descartes, Tomás de Aquino o Nietzsche) y redacta en 8-10 líneas su postura, dejando claro si se trata de una prueba a favor de la existencia de Dios o de un diagnóstico sobre la pérdida de esa creencia.$mkd$, $mkd$⚠️ No trates la postura de Nietzsche como si fuera "una prueba más" de que Dios no existe — su argumento es de otro tipo (cultural e histórico), y tratarlo como si compitiera directamente con las pruebas racionales de Descartes o Tomás de Aquino es un error habitual.$mkd$, 'f594a46d-fb21-4c60-a9cd-584ac906d75c'::uuid, 'draft'),
  ('historia_filosofia', 'Problemas Transversales', 'problemas-transversales', 18, 'Conocimiento y/o Realidad', $mkd$El problema del conocimiento y la realidad es, con diferencia, el que más autores del temario de Madrid permite elegir — hasta cinco — así que aquí es todavía más importante tener claras las diferencias antes de decidir con cuál responder.

**Descartes** busca una base racional segura para el conocimiento: mediante la duda metódica, encuentra en el cogito la primera certeza indudable, y a partir de ahí reconstruye el resto del conocimiento clasificando el origen de las ideas. **Platón** sostiene que conocer es en realidad **recordar**: el alma, antes de unirse al cuerpo, tuvo contacto directo con las Ideas eternas, y lo que llamamos aprender es recuperar ese conocimiento olvidado al nacer. **Hume**, desde el extremo opuesto, defiende que todo conocimiento procede de la experiencia sensible, y aplica esta idea de forma especialmente crítica a la causalidad: no percibimos ninguna conexión necesaria entre causa y efecto, solo la costumbre de verlos seguidos. **Kant** intenta superar el enfrentamiento entre racionalistas como Descartes y empiristas como Hume: los juicios sintéticos a priori combinan información nueva sobre el mundo con validez universal y necesaria. Y **Ortega y Gasset**, ya en el siglo XX, defiende el perspectivismo: todo conocimiento se produce desde un punto de vista concreto, y la verdad no consiste en eliminar los puntos de vista sino en sumarlos.

Para elegir con cuál responder, identifica qué modelo controlas mejor: certeza racional interior (Descartes), recuerdo de un conocimiento previo del alma (Platón), origen empírico y crítica a la causalidad (Hume), síntesis entre razón y experiencia (Kant), o conocimiento como perspectiva (Ortega).$mkd$, $mkd$Ejemplo de elección razonada: si el examen no da pistas sobre qué autor se espera y controlas bien la distinción entre juicios analíticos/sintéticos y a priori/a posteriori, Kant suele ser una opción sólida porque su posición se puede presentar como una síntesis entre las otras dos grandes familias (racionalismo y empirismo), lo cual además permite mencionar de pasada a Descartes o Hume para enriquecer la respuesta.$mkd$, $mkd$Elige uno de los cinco autores del temario que tratan el problema del conocimiento (Descartes, Platón, Hume, Kant u Ortega y Gasset) y redacta en 8-10 líneas su postura central, indicando si el origen del conocimiento está, según ese autor, en la razón, en los sentidos, o en una combinación de ambos.$mkd$, NULL, '07633129-cbf0-48cf-9bae-7663e5dfa24b'::uuid, 'draft');
