-- Contenido piloto del glosario interactivo de fórmulas para Física (93
-- entradas, 46 de las 57 fichas — las fichas puramente conceptuales sin
-- fórmula numérica quedan sin entradas a propósito). Cada símbolo está
-- ligado a su topic_id real de curriculum_topics (mismo símbolo puede
-- repetirse en varios topic_id con significados distintos, ej. "E" =
-- campo eléctrico en Electricidad vs. energía total en Relatividad vs.
-- energía del fotón en Física Cuántica). Cada 'symbol' es una subcadena
-- LaTeX literal verificada programáticamente contra el contenido real de
-- curriculum_content_v2 antes de insertar (ver auditoría/informe previo) —
-- el sistema de anotación hace coincidencia de texto exacto, no parseo
-- semántico de LaTeX. Ya aplicado en directo contra Supabase con
-- SUPABASE_SERVICE_ROLE_KEY antes de este commit; esta migración deja
-- constancia reproducible del contenido.

INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('41ae1da2-bf68-47e3-a9d8-93a155eac90f'::uuid, $glossary$G$glossary$, $glossary$Constante de gravitación universal$glossary$, $glossary$Constante física (6,674×10⁻¹¹ N·m²/kg²) que determina la intensidad de la fuerza gravitatoria entre dos masas.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('41ae1da2-bf68-47e3-a9d8-93a155eac90f'::uuid, $glossary$M$glossary$, $glossary$Masa que crea el campo$glossary$, $glossary$La masa mayor (por ejemplo, la Tierra) que genera la fuerza gravitatoria sobre la otra masa.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('41ae1da2-bf68-47e3-a9d8-93a155eac90f'::uuid, $glossary$m$glossary$, $glossary$Masa sobre la que actúa la fuerza$glossary$, $glossary$La masa del cuerpo (por ejemplo, un satélite) que sufre la atracción gravitatoria de M.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('41ae1da2-bf68-47e3-a9d8-93a155eac90f'::uuid, $glossary$r$glossary$, $glossary$Distancia entre las masas$glossary$, $glossary$Distancia entre los centros de las dos masas que interaccionan gravitatoriamente.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1e40c227-c2d1-4941-aa80-3f5b89778805'::uuid, $glossary$g$glossary$, $glossary$Intensidad del campo gravitatorio$glossary$, $glossary$Fuerza gravitatoria por unidad de masa en un punto del espacio; en la superficie terrestre coincide con la aceleración de la gravedad.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1e40c227-c2d1-4941-aa80-3f5b89778805'::uuid, $glossary$M_T$glossary$, $glossary$Masa de la Tierra$glossary$, $glossary$Masa del planeta Tierra, el cuerpo que crea el campo gravitatorio en este ejemplo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1e40c227-c2d1-4941-aa80-3f5b89778805'::uuid, $glossary$R_T$glossary$, $glossary$Radio de la Tierra$glossary$, $glossary$Distancia desde el centro de la Tierra hasta un punto de su superficie.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('8f998f65-9506-481b-b94c-7c302956e289'::uuid, $glossary$T$glossary$, $glossary$Periodo orbital$glossary$, $glossary$Tiempo que tarda un cuerpo en completar una vuelta completa a su órbita.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('8f998f65-9506-481b-b94c-7c302956e289'::uuid, $glossary$a$glossary$, $glossary$Semieje mayor de la órbita$glossary$, $glossary$Mitad del eje más largo de la elipse que describe la órbita; en una órbita circular coincide con el radio.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('8f998f65-9506-481b-b94c-7c302956e289'::uuid, $glossary$M_T$glossary$, $glossary$Masa de la Tierra$glossary$, $glossary$Masa del cuerpo central (la Tierra) alrededor del cual orbita el satélite o la Luna.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1ab96a5e-449f-4d39-8d9d-bc1a43a73602'::uuid, $glossary$E_p$glossary$, $glossary$Energía potencial gravitatoria$glossary$, $glossary$Energía que posee una masa por su posición dentro de un campo gravitatorio; determina el trabajo realizado por el campo entre dos puntos.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('e07a2cfb-d81a-4ce2-86df-42785f04552f'::uuid, $glossary$E_p$glossary$, $glossary$Energía potencial gravitatoria$glossary$, $glossary$Energía asociada a la posición de una masa m en el campo creado por M; siempre negativa y nula en el infinito.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('54f98bbc-412c-4ceb-aa3f-4d9e76d2e616'::uuid, $glossary$V$glossary$, $glossary$Potencial gravitatorio$glossary$, $glossary$Energía potencial gravitatoria por unidad de masa en un punto del campo; se mide en J/kg.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('a1358819-8498-4339-94dc-2ccf08b96e8d'::uuid, $glossary$E_m$glossary$, $glossary$Energía mecánica orbital$glossary$, $glossary$Suma de la energía cinética y potencial de un cuerpo en el campo gravitatorio; para una órbita ligada es siempre negativa y se conserva si no hay rozamiento.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('b8dc7429-d558-4450-a341-69d321fb9588'::uuid, $glossary$v_{esc}$glossary$, $glossary$Velocidad de escape$glossary$, $glossary$Velocidad mínima que necesita un objeto para escapar del campo gravitatorio de un cuerpo y alcanzar el infinito con velocidad nula.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('b8dc7429-d558-4450-a341-69d321fb9588'::uuid, $glossary$R$glossary$, $glossary$Radio del cuerpo$glossary$, $glossary$Distancia desde el centro del cuerpo (por ejemplo, la Tierra o la Luna) hasta el punto de la superficie desde donde se lanza el objeto.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('cc6b137e-e1dd-4191-a39e-7ad1b1eadc39'::uuid, $glossary$K$glossary$, $glossary$Constante de Coulomb$glossary$, $glossary$Constante física (9×10⁹ N·m²/C² en el vacío) que determina la intensidad de la fuerza eléctrica entre dos cargas.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('cc6b137e-e1dd-4191-a39e-7ad1b1eadc39'::uuid, $glossary$q_1$glossary$, $glossary$Primera carga eléctrica$glossary$, $glossary$Una de las dos cargas puntuales que interaccionan mediante la fuerza de Coulomb.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('cc6b137e-e1dd-4191-a39e-7ad1b1eadc39'::uuid, $glossary$q_2$glossary$, $glossary$Segunda carga eléctrica$glossary$, $glossary$La otra carga puntual que interacciona con q_1; su signo determina si la fuerza es atractiva o repulsiva.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('109b140a-5489-4ff2-8775-ec8010fe861e'::uuid, $glossary$E$glossary$, $glossary$Campo eléctrico$glossary$, $glossary$Fuerza eléctrica por unidad de carga positiva en un punto del espacio, creada por una carga Q.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('109b140a-5489-4ff2-8775-ec8010fe861e'::uuid, $glossary$Q$glossary$, $glossary$Carga que crea el campo$glossary$, $glossary$Carga eléctrica puntual que genera el campo eléctrico en el punto estudiado.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('47109014-dcca-4e14-891b-91b28a1864ba'::uuid, $glossary$\Phi_E$glossary$, $glossary$Flujo eléctrico$glossary$, $glossary$Medida de cuántas líneas de campo eléctrico atraviesan una superficie cerrada; se relaciona con la carga encerrada por el Teorema de Gauss.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('47109014-dcca-4e14-891b-91b28a1864ba'::uuid, $glossary$\varepsilon_0$glossary$, $glossary$Permitividad del vacío$glossary$, $glossary$Constante física que aparece en el Teorema de Gauss y relaciona el flujo eléctrico con la carga encerrada.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('47109014-dcca-4e14-891b-91b28a1864ba'::uuid, $glossary$Q_{encerrada}$glossary$, $glossary$Carga encerrada$glossary$, $glossary$Carga eléctrica total contenida dentro de la superficie gaussiana elegida.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('2cdfdc29-533b-4a3d-91de-2dc629cd0b5c'::uuid, $glossary$V$glossary$, $glossary$Potencial eléctrico$glossary$, $glossary$Energía potencial eléctrica por unidad de carga en un punto; puede ser positivo o negativo según el signo de la carga que lo crea.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('131910ca-f1b7-4721-9800-2e354e64fa7b'::uuid, $glossary$B$glossary$, $glossary$Campo magnético$glossary$, $glossary$Magnitud vectorial (medida en teslas) que describe la intensidad del campo magnético creado por una corriente eléctrica.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('131910ca-f1b7-4721-9800-2e354e64fa7b'::uuid, $glossary$\mu_0$glossary$, $glossary$Permeabilidad magnética del vacío$glossary$, $glossary$Constante física que determina la intensidad del campo magnético creado por una corriente en el vacío.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('131910ca-f1b7-4721-9800-2e354e64fa7b'::uuid, $glossary$I$glossary$, $glossary$Intensidad de corriente$glossary$, $glossary$Corriente eléctrica que circula por el hilo, espira o solenoide y que genera el campo magnético.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('131910ca-f1b7-4721-9800-2e354e64fa7b'::uuid, $glossary$n$glossary$, $glossary$Espiras por unidad de longitud$glossary$, $glossary$Número de vueltas de un solenoide dividido entre su longitud; determina la intensidad del campo en su interior.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('131910ca-f1b7-4721-9800-2e354e64fa7b'::uuid, $glossary$d$glossary$, $glossary$Distancia al hilo$glossary$, $glossary$Distancia desde el hilo rectilíneo hasta el punto donde se calcula el campo magnético.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('03eac094-8f2c-41f0-84ac-bce4c068816b'::uuid, $glossary$q$glossary$, $glossary$Carga en movimiento$glossary$, $glossary$Carga eléctrica que se mueve dentro de un campo magnético y sobre la que actúa la fuerza de Lorentz.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('03eac094-8f2c-41f0-84ac-bce4c068816b'::uuid, $glossary$r$glossary$, $glossary$Radio de la trayectoria circular$glossary$, $glossary$Radio de la circunferencia que describe una carga al moverse perpendicularmente a un campo magnético uniforme.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('a7e9be5c-a246-405b-b681-384a2a0af653'::uuid, $glossary$L$glossary$, $glossary$Longitud del conductor$glossary$, $glossary$Longitud del tramo de conductor rectilíneo por el que circula la corriente dentro del campo magnético.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('686dc362-2d1b-4abb-99b9-10c1dfca6903'::uuid, $glossary$\Phi_B$glossary$, $glossary$Flujo magnético$glossary$, $glossary$Medida de cuántas líneas de campo magnético atraviesan una superficie; su variación en el tiempo induce una fuerza electromotriz.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('686dc362-2d1b-4abb-99b9-10c1dfca6903'::uuid, $glossary$N$glossary$, $glossary$Número de espiras$glossary$, $glossary$Número de vueltas de la bobina; cuantas más espiras, mayor es la fuerza electromotriz inducida.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('686dc362-2d1b-4abb-99b9-10c1dfca6903'::uuid, $glossary$\varepsilon$glossary$, $glossary$Fuerza electromotriz inducida$glossary$, $glossary$Tensión inducida en un circuito por la variación del flujo magnético que lo atraviesa (Ley de Faraday-Henry).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('686dc362-2d1b-4abb-99b9-10c1dfca6903'::uuid, $glossary$S$glossary$, $glossary$Área de la superficie$glossary$, $glossary$Área de la espira o bobina atravesada por el campo magnético, usada para calcular el flujo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('c127a4b6-3004-4387-8241-4190804e4fed'::uuid, $glossary$\varepsilon_0$glossary$, $glossary$FEM máxima$glossary$, $glossary$Valor máximo de la fuerza electromotriz sinusoidal generada por una bobina que gira dentro de un campo magnético.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('c127a4b6-3004-4387-8241-4190804e4fed'::uuid, $glossary$\omega$glossary$, $glossary$Velocidad angular de giro$glossary$, $glossary$Rapidez con la que gira la bobina del generador, en radianes por segundo; determina la frecuencia de la corriente alterna.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4997b13e-2c11-4c0e-a9c0-860b35567b61'::uuid, $glossary$A$glossary$, $glossary$Amplitud$glossary$, $glossary$Elongación máxima que alcanza el cuerpo respecto a la posición de equilibrio durante el movimiento armónico simple.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4997b13e-2c11-4c0e-a9c0-860b35567b61'::uuid, $glossary$\omega$glossary$, $glossary$Frecuencia angular$glossary$, $glossary$Magnitud que indica la rapidez de la oscilación, relacionada con el periodo mediante ω = 2π/T.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4997b13e-2c11-4c0e-a9c0-860b35567b61'::uuid, $glossary$\varphi_0$glossary$, $glossary$Fase inicial$glossary$, $glossary$Ángulo que indica en qué punto de la oscilación se encuentra el cuerpo en el instante t = 0.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('5b0dd885-19dd-4305-9678-47151e6da5e4'::uuid, $glossary$v_{max}$glossary$, $glossary$Velocidad máxima$glossary$, $glossary$Máxima velocidad que alcanza el cuerpo en un MAS, que se produce al pasar por el punto de equilibrio (x = 0).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('5b0dd885-19dd-4305-9678-47151e6da5e4'::uuid, $glossary$a_{max}$glossary$, $glossary$Aceleración máxima$glossary$, $glossary$Máxima aceleración que alcanza el cuerpo en un MAS, que se produce en los extremos de la trayectoria (x = ±A).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('425e2450-48d7-482f-a6be-ef27b1fb7063'::uuid, $glossary$k$glossary$, $glossary$Constante elástica$glossary$, $glossary$Magnitud que mide la rigidez del muelle; a mayor k, más fuerza recuperadora ejerce ante una misma elongación (Ley de Hooke).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('d70b8f0c-c10c-4bf4-9568-a84d1a31719a'::uuid, $glossary$E_m$glossary$, $glossary$Energía mecánica del oscilador$glossary$, $glossary$Suma constante de la energía cinética y potencial elástica de un oscilador armónico simple, que se conserva a lo largo del movimiento.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('fcdd8341-5eda-44c4-a859-4c717fe8e45a'::uuid, $glossary$L$glossary$, $glossary$Longitud del hilo$glossary$, $glossary$Longitud del hilo del péndulo; junto con la gravedad, es la única magnitud de la que depende el periodo (para ángulos pequeños).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('fcdd8341-5eda-44c4-a859-4c717fe8e45a'::uuid, $glossary$T$glossary$, $glossary$Periodo del péndulo$glossary$, $glossary$Tiempo que tarda el péndulo en completar una oscilación completa.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('fcdd8341-5eda-44c4-a859-4c717fe8e45a'::uuid, $glossary$g$glossary$, $glossary$Aceleración de la gravedad$glossary$, $glossary$Intensidad del campo gravitatorio del astro donde oscila el péndulo; cambia entre la Tierra y la Luna.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('e5ab6796-542a-40aa-91da-4b40a739dfe1'::uuid, $glossary$k$glossary$, $glossary$Número de onda$glossary$, $glossary$Magnitud que indica cuántos radianes de fase hay por unidad de longitud (k = 2π/λ); no debe confundirse con la constante elástica del muelle, aunque comparten letra.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('e5ab6796-542a-40aa-91da-4b40a739dfe1'::uuid, $glossary$\lambda$glossary$, $glossary$Longitud de onda$glossary$, $glossary$Distancia entre dos puntos consecutivos de la onda que vibran exactamente igual (por ejemplo, entre dos crestas).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('e5ab6796-542a-40aa-91da-4b40a739dfe1'::uuid, $glossary$f$glossary$, $glossary$Frecuencia$glossary$, $glossary$Número de oscilaciones completas de la onda por unidad de tiempo, medida en hercios (Hz).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('89529a77-b80e-46b5-8b67-679e79e80ecd'::uuid, $glossary$I$glossary$, $glossary$Intensidad de la onda$glossary$, $glossary$Potencia que transporta la onda por unidad de área perpendicular a la propagación.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('89529a77-b80e-46b5-8b67-679e79e80ecd'::uuid, $glossary$P$glossary$, $glossary$Potencia$glossary$, $glossary$Energía que transporta la onda por unidad de tiempo a través de la superficie considerada.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('eb4f6c6a-2a0f-4ba5-951a-151b09db89bd'::uuid, $glossary$\beta$glossary$, $glossary$Nivel de intensidad sonora$glossary$, $glossary$Medida logarítmica (en decibelios) de cuán intenso es un sonido en comparación con la intensidad umbral de audición I_0.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('eb4f6c6a-2a0f-4ba5-951a-151b09db89bd'::uuid, $glossary$I_0$glossary$, $glossary$Intensidad umbral de referencia$glossary$, $glossary$Intensidad mínima de sonido que el oído humano puede percibir (10⁻¹² W/m²), usada como referencia para medir decibelios.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('b88ac029-6131-409e-8ece-028ca2582e57'::uuid, $glossary$f'$glossary$, $glossary$Frecuencia percibida$glossary$, $glossary$Frecuencia del sonido tal como la percibe el observador, distinta de la frecuencia real emitida por la fuente cuando hay movimiento relativo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('b88ac029-6131-409e-8ece-028ca2582e57'::uuid, $glossary$v_f$glossary$, $glossary$Velocidad de la fuente$glossary$, $glossary$Velocidad a la que se mueve la fuente sonora (por ejemplo, la sirena de una ambulancia) respecto al observador.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('077d00b5-9435-4047-b910-458da15889e8'::uuid, $glossary$c$glossary$, $glossary$Velocidad de la luz en el vacío$glossary$, $glossary$Velocidad a la que se propaga la luz en el vacío (3×10⁸ m/s), la velocidad máxima posible en el universo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('bf427ecb-37dc-4ce5-9530-f41792527fd0'::uuid, $glossary$n$glossary$, $glossary$Índice de refracción$glossary$, $glossary$Número que indica cuánto se frena la luz en un medio comparado con el vacío; siempre es mayor o igual a 1.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('73d6cd11-faed-4eb5-b3eb-f99a6870bcd1'::uuid, $glossary$\hat i$glossary$, $glossary$Ángulo de incidencia$glossary$, $glossary$Ángulo que forma el rayo incidente con la normal (la perpendicular) a la superficie del espejo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('73d6cd11-faed-4eb5-b3eb-f99a6870bcd1'::uuid, $glossary$\hat r$glossary$, $glossary$Ángulo de reflexión$glossary$, $glossary$Ángulo que forma el rayo reflejado con la normal; en la reflexión es siempre igual al ángulo de incidencia.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('10257bdf-b4b1-4ad9-80f6-91bd3ac7f03e'::uuid, $glossary$n_1$glossary$, $glossary$Índice de refracción del primer medio$glossary$, $glossary$Índice de refracción del medio del que procede el rayo de luz antes de cambiar de medio.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('10257bdf-b4b1-4ad9-80f6-91bd3ac7f03e'::uuid, $glossary$n_2$glossary$, $glossary$Índice de refracción del segundo medio$glossary$, $glossary$Índice de refracción del medio al que entra el rayo de luz tras refractarse.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('bbf061a0-0474-43a8-8fc8-7daf7b80a9ed'::uuid, $glossary$\hat L$glossary$, $glossary$Ángulo límite$glossary$, $glossary$Ángulo de incidencia a partir del cual toda la luz se refleja por completo en vez de refractarse, al pasar de un medio más denso a uno menos denso.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('0706dd62-5011-4c7b-bddd-55dc0294d8f6'::uuid, $glossary$s$glossary$, $glossary$Posición del objeto$glossary$, $glossary$Distancia (con signo) desde el centro de la lente hasta el objeto, medida según el criterio de signos habitual.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('0706dd62-5011-4c7b-bddd-55dc0294d8f6'::uuid, $glossary$s'$glossary$, $glossary$Posición de la imagen$glossary$, $glossary$Distancia (con signo) desde el centro de la lente hasta la imagen formada.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('0706dd62-5011-4c7b-bddd-55dc0294d8f6'::uuid, $glossary$f'$glossary$, $glossary$Distancia focal$glossary$, $glossary$Distancia característica de la lente que determina su capacidad para converger o divergir los rayos de luz; positiva en lentes convergentes, negativa en divergentes.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('bcf25cf1-da78-4155-a95d-92d907062e14'::uuid, $glossary$m$glossary$, $glossary$Aumento lateral$glossary$, $glossary$Cociente entre el tamaño de la imagen y el del objeto; su valor absoluto indica cuánto se agranda o reduce la imagen, y su signo si está invertida.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('645a364e-84cb-4d4c-a86f-45b91a578835'::uuid, $glossary$P$glossary$, $glossary$Potencia de una lente$glossary$, $glossary$Capacidad de convergencia o divergencia de una lente, medida en dioptrías como el inverso de la distancia focal en metros.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('d6184dec-ada2-44c3-9955-6dd322710be9'::uuid, $glossary$t_0$glossary$, $glossary$Tiempo propio$glossary$, $glossary$Tiempo medido por un observador que viaja junto al reloj, en su mismo sistema de referencia.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('d6184dec-ada2-44c3-9955-6dd322710be9'::uuid, $glossary$\gamma$glossary$, $glossary$Factor de Lorentz$glossary$, $glossary$Factor mayor que 1 que mide cuánto se dilata el tiempo (o se contrae la longitud) para un observador respecto al cual algo se mueve a velocidad v cercana a c.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('a3a420f7-b689-493e-90c8-c1ca9a489f1c'::uuid, $glossary$L_0$glossary$, $glossary$Longitud propia$glossary$, $glossary$Longitud de un objeto medida por un observador en reposo respecto a él; es la longitud máxima que puede medirse.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('a564399b-c98a-4e76-b222-9d982d36b560'::uuid, $glossary$E_0$glossary$, $glossary$Energía en reposo$glossary$, $glossary$Energía que posee un cuerpo de masa m por el mero hecho de tener masa, incluso si está en reposo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('3ae5f585-1b96-41b9-84e8-7f033e23da4a'::uuid, $glossary$E$glossary$, $glossary$Energía total relativista$glossary$, $glossary$Suma de la energía en reposo y la energía cinética de una partícula, válida a cualquier velocidad, incluidas las cercanas a c.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('3ae5f585-1b96-41b9-84e8-7f033e23da4a'::uuid, $glossary$p$glossary$, $glossary$Momento lineal relativista$glossary$, $glossary$Cantidad de movimiento de una partícula calculada con el factor de Lorentz, válida también a velocidades cercanas a c.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('3ae5f585-1b96-41b9-84e8-7f033e23da4a'::uuid, $glossary$E_c$glossary$, $glossary$Energía cinética relativista$glossary$, $glossary$Energía cinética de una partícula calculada correctamente a velocidades cercanas a c, distinta de la fórmula clásica ½mv².$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('98fdf2ba-e5d2-4100-8730-cc2a76e21751'::uuid, $glossary$h$glossary$, $glossary$Constante de Planck$glossary$, $glossary$Constante física (6,63×10⁻³⁴ J·s) que relaciona la energía de un cuanto de luz con su frecuencia.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1f7dbded-6699-45b5-b677-67be79bcacda'::uuid, $glossary$W_0$glossary$, $glossary$Trabajo de extracción$glossary$, $glossary$Energía mínima necesaria para arrancar un electrón de la superficie de un metal.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1f7dbded-6699-45b5-b677-67be79bcacda'::uuid, $glossary$E_{c,max}$glossary$, $glossary$Energía cinética máxima del electrón arrancado$glossary$, $glossary$Energía cinética que le queda al electrón tras ser arrancado del metal, una vez descontado el trabajo de extracción.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('1f7dbded-6699-45b5-b677-67be79bcacda'::uuid, $glossary$f_0$glossary$, $glossary$Frecuencia umbral$glossary$, $glossary$Frecuencia mínima de la luz incidente necesaria para que se produzca efecto fotoeléctrico en un metal concreto.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('b870689c-bde9-4c76-b0e4-09937bab8443'::uuid, $glossary$\lambda$glossary$, $glossary$Longitud de onda de De Broglie$glossary$, $glossary$Longitud de onda asociada a cualquier partícula con cantidad de movimiento p, según la dualidad onda-corpúsculo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('7fdb2707-c33d-4b0e-91fa-9fc75f20789c'::uuid, $glossary$\Delta x$glossary$, $glossary$Incertidumbre en la posición$glossary$, $glossary$Margen de imprecisión con el que se puede conocer la posición de una partícula cuántica.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('7fdb2707-c33d-4b0e-91fa-9fc75f20789c'::uuid, $glossary$\Delta p$glossary$, $glossary$Incertidumbre en el momento$glossary$, $glossary$Margen de imprecisión con el que se puede conocer la cantidad de movimiento de una partícula cuántica; cuanto menor es Δx, mayor es Δp.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('27bc2083-8db5-4ee9-ab58-9309dda4d413'::uuid, $glossary$E_{final}$glossary$, $glossary$Energía del nivel final$glossary$, $glossary$Energía de la órbita a la que salta el electrón (más baja en una emisión, más alta en una absorción).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('27bc2083-8db5-4ee9-ab58-9309dda4d413'::uuid, $glossary$E_{inicial}$glossary$, $glossary$Energía del nivel inicial$glossary$, $glossary$Energía de la órbita en la que se encuentra el electrón antes de emitir o absorber un fotón.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4746f828-9991-46e0-8c8f-94e8c09cd832'::uuid, $glossary$Z$glossary$, $glossary$Número atómico$glossary$, $glossary$Número de protones del núcleo; identifica de qué elemento químico se trata.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4746f828-9991-46e0-8c8f-94e8c09cd832'::uuid, $glossary$A$glossary$, $glossary$Número másico$glossary$, $glossary$Suma del número de protones y neutrones del núcleo (nucleones totales).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('c73c54bb-0db5-4b0b-8e55-3bdb713695d5'::uuid, $glossary$\Delta m$glossary$, $glossary$Defecto de masa$glossary$, $glossary$Diferencia entre la masa de un núcleo y la suma de las masas de sus nucleones por separado; equivale a la energía de enlace.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('c73c54bb-0db5-4b0b-8e55-3bdb713695d5'::uuid, $glossary$E_{enlace}$glossary$, $glossary$Energía de enlace nuclear$glossary$, $glossary$Energía necesaria para separar completamente los nucleones de un núcleo; cuanto mayor es por nucleón, más estable es el núcleo.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4f7c1299-9440-409a-945e-5ff253a59cce'::uuid, $glossary$N_0$glossary$, $glossary$Número inicial de núcleos$glossary$, $glossary$Cantidad de núcleos radiactivos presentes en la muestra en el instante inicial (t = 0).$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4f7c1299-9440-409a-945e-5ff253a59cce'::uuid, $glossary$\lambda$glossary$, $glossary$Constante de desintegración$glossary$, $glossary$Magnitud que mide la rapidez con la que se desintegra un isótopo radiactivo; a mayor λ, más rápida es la desintegración.$glossary$);
INSERT INTO formula_glossary (topic_id, symbol, label, definition) VALUES ('4f7c1299-9440-409a-945e-5ff253a59cce'::uuid, $glossary$T_{1/2}$glossary$, $glossary$Periodo de semidesintegración$glossary$, $glossary$Tiempo que tarda en desintegrarse la mitad de los núcleos de una muestra radiactiva.$glossary$);
