-- Auditoría pedagógica de contenido de Inglés y Historia de la Filosofía.
-- Todas las correcciones son UPDATE sobre curriculum_content_v2 existente — no se toca
-- topic_id, review_status, ni la estructura de topics (salvo 1 topic nuevo de Inglés,
-- ver migración separada 20260903100000). review_status sigue en 'draft'.
--
-- INGLÉS:
-- - T/F (2): añade el formato Not Given (2025-2026) — solo 2 de 3 afirmaciones, evidencia
--   solo para T/F, nunca para NG.
-- - Gramática general (5): referencia el nuevo topic de gerundio/infinitivo.
-- - Ensayo de opinión (6): el rango "150-200 palabras" no es universal — el modelo 2026
--   pide 140-180 (verificado en ingles.ts). Se quita también del título del topic.
-- - Estilo Indirecto (7): el backshift se explica como patrón habitual, no automático
--   universal; se añaden preguntas de sí/no (if/whether) y órdenes reportadas — ambas
--   aparecen repetidamente en el banco real y faltaban por completo en la ficha.
-- - Condicionales (8): el ejemplo de condicional mixta ("she would marry him") no
--   marcaba el tiempo presente de la consecuencia — se sustituye por un ejemplo
--   inequívoco con "now" y se aclara que las mixtas son minoritarias frente a las 3
--   básicas.
-- - Voz Pasiva (9): se explicita que una cláusula de relativo reducida ("the book,
--   written by...") no es una pasiva completa con "to be", aunque se reconozca igual.
-- - Narrativa (11): se reconoce que ~3 de los 9 prompts son más "describe tu cosa
--   favorita y por qué" que narrativa de experiencia personal — variante real, no
--   inventada.
-- - Email informal (12): se precisa que aparece en 4 de las 5 convocatorias 2025-2026
--   (todas menos la Extraordinaria 2025), no en todas.
--
-- HISTORIA DE LA FILOSOFÍA:
-- - Los 13 autores: "Los textos de X en el examen vienen de..." se reformula como
--   constatación del corpus cargado ("En el banco PAU Madrid actualmente incluido en
--   Kairo..."), no como regla sobre qué obra puede usar el autor en el examen real.
--   "Fragmento típico: '...'" se relabela como "Ejemplo didáctico (parafraseado):" —
--   ninguno de esos fragmentos es una cita literal del banco real, son paráfrasis
--   propias construidas para ilustrar el tipo de argumento (evita que parezcan citas).
-- - Los 5 problemas transversales: reescritos por completo — la estrategia de examen
--   pasa de "elige el autor que mejor domines" a "identifica la época pedida y elige
--   solo entre los autores de esa época dentro del roster del topic"; se documenta
--   explícitamente cada hueco de época real detectado (ética moderna, sociedad/política
--   antigua-medieval, ser humano moderna, conocimiento medieval) en vez de ocultarlo.

UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En esta tarea se dan afirmaciones sobre el texto y hay que decidir si son **verdaderas o falsas**, copiando además la frase exacta del texto que lo demuestra — sin esa cita, la respuesta correcta no puntúa, aunque el verdadero/falso esté bien.

Antes de leer el texto entero, conviene leer primero las afirmaciones: así sabes qué buscar y puedes hacer una lectura de **scanning** (localizar información concreta) en vez de leer todo con el mismo detalle. Las afirmaciones suelen ir en el mismo orden que la información aparece en el texto.

Dos trampas habituales: afirmaciones que invierten el sentido real de una frase (niegan algo que el texto afirma, o al revés), y afirmaciones que mezclan un dato verdadero con otro inventado en la misma frase — si una sola parte es falsa, toda la afirmación es falsa. La cita que copies debe ser la frase completa que sirve de prueba, no una palabra suelta.

**Formato con Not Given** (aparece en los exámenes 2025-2026 disponibles en el banco): se añade una tercera opción, "Not Given" (la información no aparece en el texto, ni para confirmarla ni para negarla), y solo hay que responder 2 de las 3 afirmaciones propuestas, no las 3. La evidencia textual solo se pide para las respuestas True o False — si respondes Not Given, no hay ninguna frase que citar, porque precisamente el texto no dice nada sobre eso.$mkd$, worked_example_markdown = $mkd$Texto (fragmento): "Although the bridge was built in 1920, it was not officially opened to the public until three years later, due to funding problems."

Afirmación: "The bridge was opened the same year it was built." → **FALSE**. Evidencia: "it was not officially opened to the public until three years later".

Nótese que copiar solo "1920" no sirve como evidencia — hay que copiar la frase que demuestra que la afirmación es falsa, no solo el dato numérico. Si la afirmación fuera, por ejemplo, "The bridge cost more than expected to build" y el texto no mencionara nada sobre el coste, la respuesta sería **Not Given** — no hace falta (ni es posible) copiar ninguna evidencia en ese caso.$mkd$, practice_prompt = $mkd$Texto: "Marta learned to swim when she was six, but she didn't compete professionally until her twenties, after years of training with a local club."
Afirmación: "Marta started competing professionally as soon as she learned to swim."
¿Verdadero o falso? Copia la evidencia exacta del texto.$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 2;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Esta tarea da frases con huecos y una palabra entre paréntesis que hay que usar en la forma correcta — un mismo apartado suele mezclar varios puntos distintos (una preposición, un tiempo verbal, un comparativo, gerundio/infinitivo...), así que conviene resolver cada hueco por separado en vez de intentar entender la frase entera de golpe.

Casi todos los exámenes incluyen un apartado dedicado a transformar una pregunta o afirmación en **estilo indirecto** — revisa el topic específico de Estilo Indirecto para el detalle completo del backshift, las preguntas de sí/no y las órdenes reportadas. Otros apartados frecuentes tienen su propio topic: condicionales, voz pasiva, comparativos/superlativos y gerundio vs. infinitivo — repásalos si fallas un hueco de ese tipo concreto.

Para los huecos que no encajan en ninguno de esos topics (una preposición fija, una forma verbal simple): primero identifica qué tipo de palabra falta, completa, y relee la frase entera al final para comprobar que tiene sentido y concuerda en persona y número.$mkd$, worked_example_markdown = $mkd$a) Complete: "If I _______ (know) about the meeting, I _______ (attend) it." → "If I **had known** about the meeting, I **would have attended** it." (condicional de tercer tipo: situación hipotética pasada).

b) Estilo indirecto: "Where do you live?" she asked me. → She asked me **where I lived**. (el tiempo retrocede de presente a pasado, y el orden pasa a ser afirmativo: "where I lived", no "where did I live").$mkd$, practice_prompt = $mkd$Completa usando la forma correcta:
a) The article was _______ (write) by a journalist who _______ (interview) over fifty witnesses.
b) Complete la frase para reportar lo dicho: "Have you finished your homework?" my mother asked. — My mother asked me _____________________________ .$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 5;
UPDATE curriculum_content_v2 SET title = 'Redacción: Ensayo de Opinión', concept_markdown = $mkd$Esta tarea pide dar tu opinión sobre un tema en un número de palabras concreto. En la mayoría de las convocatorias del banco (2018-2025) el enunciado pide **150 a 200 palabras**, pero el modelo más reciente disponible (2026) pide **140 a 180** — el rango exacto lo da siempre el enunciado del examen que tengas delante, así que léelo con atención en vez de memorizar un único número. Se valora el contenido (que respondas realmente a lo que se pregunta), la organización del texto, y el uso correcto y variado del inglés — no hace falta estar "de acuerdo" con nada en particular, solo defender una postura de forma clara.

Una estructura que funciona de forma fiable: una frase inicial que presente el tema y tu postura, dos párrafos centrales con una razón cada uno (idealmente con un ejemplo breve que la ilustre), y una frase final que cierre retomando tu opinión — no hace falta un párrafo de conclusión largo, con una frase basta.

Usar conectores (*however*, *moreover*, *for this reason*, *in conclusion*) ayuda a que el texto se lea como un argumento organizado y no como una lista de frases sueltas. Conviene controlar la longitud dentro del rango que pida tu examen: quedarse corto pierde puntos de contenido, y pasarse no suma nada extra — es mejor revisar lo escrito que añadir más frases al final.$mkd$, worked_example_markdown = $mkd$Tema: "Should students be allowed to use mobile phones in class?"

Esquema de una respuesta dentro del rango pedido (150-200 palabras en la mayoría de exámenes, 140-180 en el modelo 2026): (1) frase inicial — postura clara ("I believe mobile phones should be allowed in class, but only for specific tasks."); (2) primer párrafo — razón 1 con ejemplo (acceso rápido a información, diccionarios online); (3) segundo párrafo — razón 2 con ejemplo, o un matiz/contraargumento reconocido con "however"; (4) frase final — retoma la postura inicial con otras palabras.$mkd$, practice_prompt = $mkd$Escribe dentro del rango de palabras que pida tu examen (150-200 en la mayoría de convocatorias) sobre el siguiente tema: "Is it better to travel alone or with other people? Explain your choice."$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 6;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Al transformar una pregunta o afirmación directa en estilo indirecto (*reported speech*), ocurren varios cambios sistemáticos que aparecen repetidamente en el banco de Madrid:

**1. El tiempo verbal suele retroceder** (backshift): present simple → past simple, present perfect → past perfect, will → would, can → could, must → had to. Cuando el verbo introductor está en pasado ("she said", "he asked"), lo habitual es que el tiempo del verbo citado retroceda uno — pero no es una transformación automática en todos los casos: si lo citado sigue siendo válido en el momento de reportarlo (una verdad general, algo que aún no ha cambiado), el tiempo puede mantenerse. En el examen, aplica el backshift salvo que el sentido de la frase pida claramente lo contrario.

**2. Las preguntas cambian de orden y de tipo de conector.** Si es una pregunta Wh- ("Where do you live?"), el orden pasa a ser el de una afirmación normal y desaparecen los auxiliares de pregunta: "...where I lived" (no "...where did I live"). Si es una pregunta de sí/no ("Do you enjoy...?", "Have you finished...?"), se introduce con **if** o **whether**: "he asked me if/whether I enjoyed...".

**3. Las órdenes y peticiones** se reportan con **verbo + objeto + infinitivo con "to"**: "Stop telling me scary stories," she said → she told me **to stop telling** her scary stories.

**4. Los pronombres y marcadores de tiempo/lugar se adaptan** al punto de vista de quien informa: "today" → "that day", "tomorrow" → "the next day", "here" → "there", "my" → "her/his".$mkd$, worked_example_markdown = $mkd$Directo (pregunta Wh-): "Where do you live?" she asked me.
Indirecto: She asked me **where I lived**.

Directo (pregunta sí/no): "Do you enjoy drinking coffee after your dinner?" he asked me.
Indirecto: He asked me **if/whether I enjoyed** drinking coffee after my dinner. (se añade "if/whether" porque la pregunta original no tenía palabra Wh-, y el verbo retrocede de presente a pasado).$mkd$, practice_prompt = $mkd$Transforma a estilo indirecto: "Have you finished your homework?" my mother asked. — My mother asked me _____________________________ .$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 7;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Las oraciones condicionales relacionan una condición (cláusula con "if") con su consecuencia. Los tipos que más aparecen en el examen son:

- **Primera condicional** (condición real y futura): *if* + presente, ... + *will* + infinitivo. "If questions are asked, women are more likely to speak up."
- **Segunda condicional** (situación hipotética presente/futura, poco probable o irreal): *if* + pasado simple, ... + *would* + infinitivo. "If I were you, I would show..."
- **Tercera condicional** (situación hipotética pasada, ya no se puede cambiar): *if* + pluscuamperfecto (*had* + participio), ... + *would have* + participio. "If I had known..., I would have joined..."
- **Condicionales mixtas** (menos frecuentes que las tres anteriores, pero aparecen en el banco real): combinan una condición de un momento con una consecuencia de otro — por ejemplo, condición pasada con consecuencia presente: "If I had studied medicine, I would be a doctor now" (no estudié medicina en el pasado, y por eso no soy médico ahora — nota el "now", que marca que la consecuencia es presente, no pasada).

El error más habitual es mezclar los tiempos de la condición y la consecuencia sin darse cuenta de qué tipo de condicional pide la frase — conviene identificar primero si la situación es real, hipotética-presente o hipotética-pasada (y si la consecuencia pertenece a ese mismo momento o a otro distinto) antes de rellenar los huecos.$mkd$, worked_example_markdown = $mkd$Completa: "If I _______ (know) that this pizza had so much salt, I _______ (not/buy) it when I went to the supermarket yesterday."

La frase habla de algo que pasó "ayer" y ya no se puede cambiar → **tercera condicional**: "If I **had known** ..., I **wouldn't have bought** it..."$mkd$, practice_prompt = $mkd$Completa usando el tipo de condicional adecuado: "If she _______ (have) more free time, she _______ (learn) to play the piano."$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 8;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Se usa la voz pasiva (*to be* + participio pasado) cuando interesa más la acción o quién la recibe que quién la realiza — muy habitual en textos informativos y noticias, que es justo el tipo de texto de estos exámenes.

Para formar la pasiva: **sujeto pasivo + to be (en el tiempo correspondiente) + participio pasado (+ by + agente, si se menciona)**. El tiempo verbal de "to be" tiene que coincidir con el tiempo de la frase activa original: "wrote" (pasado simple) → "was written"; "has discovered" (presente perfecto) → "has been discovered".

En estos ejercicios, la pista entre paréntesis suele ser el verbo en infinitivo, y hay que reconocer POR EL CONTEXTO que el sujeto no realiza la acción sino que la recibe — por ejemplo, "the article _______ (write) by a journalist" solo tiene sentido si "the article" es escrito, no si escribe. Cuidado con un caso relacionado pero distinto: un participio pasado justo después de una coma, sin ningún verbo "to be" delante ("the book, written by George R.R. Martin"), no es una pasiva completa — es una **cláusula de relativo reducida** (la forma completa sería "the book, which was written by...", y se puede acortar quitando "which was"). Se reconoce igual (el sujeto recibe la acción), pero gramaticalmente no lleva "to be" propio.$mkd$, worked_example_markdown = $mkd$Completa: "The series Game of Thrones _______ (base) on the book, _______ (write) by George R.R. Martin."

La serie no "basa" nada, sino que **está basada** en el libro (pasiva presente con "to be": "**is based**"). El libro tampoco "escribe", sino que **fue escrito** por Martin — pero aquí no hace falta ningún "to be": "**written**" es un participio que funciona como cláusula de relativo reducida ("the book, written by..." = "the book, which was written by...").$mkd$, practice_prompt = $mkd$Completa: "The article _______ (write) by a journalist who _______ (interview) over fifty witnesses."$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 9;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$A diferencia del ensayo de opinión, aquí no se pide defender una postura con razones para o en contra, sino **contar o describir algo personal**: la mayoría de estos prompts narran una experiencia concreta ("Have you ever felt homesick? Describe your experience", "Describe an experience that made you feel afraid"), pero algunos piden en cambio describir algo que te gusta y explicar por qué ("What is your favourite book? Describe it and say why you like it so much") — esta segunda variante se acerca más a una descripción con justificación breve que a un relato con principio y final, así que ajusta la estructura según cuál de las dos te pidan.

Para la narración de una experiencia, la estructura que funciona bien es cronológica: una frase inicial que sitúe la situación (cuándo, dónde, qué pasaba), un desarrollo que cuente qué ocurrió y cómo te sentiste, y un cierre breve con cómo terminó o qué aprendiste. Aquí sí conviene usar tiempos narrativos (past simple para la acción principal, past continuous para el contexto, past perfect si hay que mencionar algo anterior a la historia) en vez de los presentes/futuros típicos de un ensayo de opinión.

Para la variante de "describe tu cosa favorita", la estructura es más simple: preséntala, descríbela con algo de detalle, y explica 1-2 razones concretas por las que te gusta. En ambos casos se sigue evaluando el rango y la corrección del inglés — no basta con contar algo simple en frases cortas; conviene incluir algún detalle sensorial o emocional que dé cuerpo al texto.$mkd$, worked_example_markdown = $mkd$Tema: "Describe an experience that made you feel afraid."

Esquema: (1) frase inicial situando el momento ("Last summer, I decided to go hiking alone in the mountains near my hometown."); (2) desarrollo narrativo con tiempos de pasado ("As it started to get dark, I realised I had lost the path..."); (3) cierre con la resolución y cómo te sentiste después.$mkd$, practice_prompt = $mkd$Escribe dentro del rango de palabras que pida tu examen (150-200 en la mayoría de convocatorias): "Have you ever lost something that was important to you? Describe your experience."$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 11;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Este formato ha empezado a aparecer como alternativa al ensayo de opinión en los exámenes más recientes disponibles en el banco: aparece en 4 de las 5 convocatorias de 2025-2026 (todas menos la Extraordinaria 2025), siempre como segunda opción junto a un ensayo de opinión — el alumno elige cuál de los dos escribir. Conviene conocerlo aunque hoy sea menos frecuente que el ensayo en el conjunto del banco.

A diferencia del ensayo, un email informal a un amigo tiene sus propias convenciones: **saludo informal** ("Hi Susan," / "Dear Tom,"), un **registro cercano** (contracciones, expresiones coloquiales, evitar un tono demasiado formal), y un **cierre informal** ("Take care," / "See you soon," seguido de una despedida) — aunque en el examen se pide explícitamente no firmar ni identificarse.

El contenido debe responder a lo que pide el enunciado (pedir consejo, dar una recomendación, contar una noticia) de forma organizada: una frase que retome el motivo del email, el contenido principal en 1-2 párrafos breves, y un cierre que invite a responder o se despida con calidez. El rango de palabras es el mismo que pida el ensayo de opinión en ese mismo examen (150-200 en la mayoría de convocatorias, 140-180 en el modelo 2026).$mkd$, worked_example_markdown = $mkd$Tarea: "Write an informal e-mail to your American friend Susan asking for advice about a trip you are planning to the USA."

Esquema: saludo informal ("Hi Susan,"); frase que sitúa el motivo ("I'm planning a trip to the USA next summer and I could really use your advice."); 1-2 preguntas concretas (dónde alojarse, qué ciudades visitar); cierre cercano invitando a responder ("Let me know what you think! Take care,").$mkd$, practice_prompt = $mkd$Escribe dentro del rango de palabras que pida tu examen: tu amiga Susan te ha escrito preguntando si debería estudiar en su país o en el extranjero. Respóndele con un email informal dándole tu consejo.$mkd$, alert_markdown = NULL WHERE subject = 'ingles' AND sort_order = 12;
UPDATE curriculum_topics SET title = 'Redacción: Ensayo de Opinión' WHERE subject = 'ingles' AND topic_slug = 'redaccion-ensayo-de-opinion';

UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Descartes provienen casi siempre de las *Meditaciones metafísicas* y giran en torno al **método de la duda** y al **cogito**. Descartes decide dudar de todo lo que pueda ser puesto en duda —los sentidos engañan a veces, y hasta las verdades matemáticas podrían ser falsas si existiera un genio maligno que nos engañara— para encontrar algo que resista cualquier duda posible.

Lo único que sobrevive a la duda es que, mientras dudo, **pienso**, y mientras pienso, **existo**: de ahí el "pienso, luego existo". A partir de esta certeza, Descartes reconstruye el conocimiento clasificando las ideas en tres tipos —**innatas** (nacen con la mente, como la idea de Dios o de sustancia), **adventicias** (parecen venir de fuera, como la idea del sol que percibo) y **facticias** (inventadas por mí, como una sirena)— y usa la idea de un ser infinito y perfecto que tengo en mí para demostrar que Dios existe: un ser finito e imperfecto como yo no podría haber producido por sí solo la idea de algo infinito y perfecto.

En el comentario de texto, lo habitual es que el fragmento se centre en UNO de estos tres momentos —la duda y el cogito, la clasificación de las ideas, o la prueba de la existencia de Dios— y hay que identificar cuál de los tres es, porque cada uno responde a una pregunta distinta.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "...advierto que, si dudo, pienso, y que mientras pienso soy algo; y aunque todo lo demás fuese engañoso, esta verdad no podría serlo."

Identificación: este fragmento pertenece al momento de la **duda metódica y el cogito** (no a la clasificación de ideas ni a la prueba de Dios), porque el argumento es exactamente "dudar → pensar → existir". En el comentario hay que explicar que la duda no es un fin en sí misma sino una herramienta: sirve para encontrar una primera verdad indudable sobre la que reconstruir el resto del conocimiento.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 1;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Tomás de Aquino provienen de la *Suma Teológica* y casi siempre presentan una de las **cinco vías** con las que demuestra racionalmente la existencia de Dios, partiendo de la observación del mundo sensible, nunca de una intuición directa. Las cinco vías comparten una misma estructura: se observa un hecho del mundo, se argumenta que la cadena de ese hecho no puede prolongarse hasta el infinito, y se concluye que tiene que haber un primer término que explique la serie sin ser él mismo parte de ella — a ese primer término lo llama Dios.

Conviene distinguirlas bien: **1ª vía** (del movimiento: todo lo que se mueve es movido por otro, tiene que haber un primer motor inmóvil); **2ª vía** (de la causa eficiente: nada es causa de sí mismo, tiene que haber una primera causa incausada); **3ª vía** (de la contingencia: todo lo que existe podría no existir, tiene que haber algo necesario); **4ª vía** (de los grados de perfección: si hay cosas más o menos buenas/verdaderas, tiene que haber un máximo del que las demás participan); **5ª vía** (del orden: las cosas sin conocimiento actúan ordenadamente hacia un fin, así que alguien inteligente las dirige).

Un segundo tipo de texto, menos frecuente pero también real en el banco de exámenes, no presenta una vía sino que discute si la existencia de Dios es "evidente por sí misma" — Tomás de Aquino distingue entre lo evidente en sí mismo (donde el predicado ya está contenido en el sujeto) y lo evidente para nosotros, y argumenta que aunque la existencia de Dios sea evidente en sí misma, el ser humano necesita demostrarla partiendo de sus efectos.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Vemos que las cosas naturales, careciendo de conocimiento, obran por un fin... luego existe un ser inteligente que dirige todas las cosas naturales a su fin."

Identificación: es la **quinta vía** (del orden o finalidad) — el argumento parte de que las cosas sin conocimiento actúan siempre o casi siempre del mismo modo para lograr lo mejor, lo cual solo se explica si algo inteligente las dirige, igual que una flecha solo llega a su blanco si alguien la dirige.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 2;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Platón provienen del *Fedón* y giran en torno a dos ideas profundamente conectadas: la **teoría de la reminiscencia** y el **dualismo entre alma y cuerpo**.

La teoría de la reminiscencia sostiene que conocer no es aprender algo nuevo, sino **recordar** algo que el alma ya conocía antes de unirse al cuerpo — por ejemplo, cuando decimos que dos palos son "iguales", aplicamos una idea de igualdad perfecta que nunca hemos visto realizada en el mundo sensible, así que esa idea tuvo que ser adquirida por el alma en un momento anterior al nacimiento, en contacto directo con las Ideas.

Esta teoría solo tiene sentido si el alma existe antes del cuerpo y es de naturaleza distinta a él: de ahí el dualismo. El cuerpo, ligado a los sentidos, ofrece un conocimiento confuso y cambiante de las cosas sensibles; el alma, cuando se libera de la influencia del cuerpo y razona por sí misma, puede acceder a las Ideas eternas e inmutables. Por eso Platón describe el cuerpo casi como un obstáculo para el alma, y la filosofía como un entrenamiento para "separarse" de él ya en vida.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Cuando el alma investiga por sí misma, se dirige a lo puro, eterno e inmortal... y esto es lo que llamamos sabiduría."

Identificación: este fragmento corresponde al **dualismo alma-cuerpo**, no a la reminiscencia — el argumento contrasta lo que ocurre cuando el alma actúa "por sí misma" (razón pura, accede a lo eterno) frente a cuando actúa "a través del cuerpo" (sentidos, mundo cambiante).$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 3;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Kant provienen de la *Crítica de la razón pura* y se centran en su pregunta central: ¿cómo es posible el conocimiento científico, y hasta dónde puede llegar la razón sin perderse en especulaciones vacías?

Para responder, Kant cruza dos parejas de conceptos: por un lado, **juicios analíticos** (el predicado ya está contenido en el sujeto, no añaden información nueva, como "todo cuerpo es extenso") frente a **juicios sintéticos** (el predicado añade algo que no estaba en el sujeto, como "este cuerpo pesa dos kilos"); por otro, **a priori** (independiente de la experiencia, universal y necesario) frente a **a posteriori** (depende de la experiencia, contingente). La ciencia, para Kant, se apoya en juicios **sintéticos a priori** — añaden información nueva pero son universales y necesarios, como las proposiciones matemáticas o el principio de causalidad.

Cuando el texto habla de la posibilidad de la metafísica, Kant advierte de que la razón tiende a usar estos mismos conceptos (causa, sustancia) más allá de toda experiencia posible —para hablar de Dios, el alma o el universo como totalidad— y ahí es donde el conocimiento deja de ser seguro: la metafísica tradicional pretende un conocimiento sintético a priori que, para Kant, no está justificado de la misma manera que en las matemáticas o la física.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Todo cuerpo es extenso es una proposición a priori porque el concepto de extensión ya está en el concepto de cuerpo; pero este cuerpo pesa dos kilos es un juicio sintético, porque el peso no está contenido en el concepto de cuerpo."

Identificación: corresponde a la distinción **analítico/sintético**, no a la de a priori/a posteriori — el criterio que se usa es si el predicado "añade" algo al concepto del sujeto, que es justamente el criterio analítico/sintético.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 4;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Rousseau provienen de *Del contrato social* y explican cómo los seres humanos, en algún momento, dejan de poder sobrevivir aislados en el estado de naturaleza y necesitan unir sus fuerzas sin perder su libertad — ese es el problema que el **contrato social** viene a resolver.

La solución de Rousseau es que cada persona se entregue **por entero** a la comunidad, sin reservarse nada para sí ni someterse a ningún otro individuo en particular: como todos se dan de la misma manera, nadie tiene interés en hacer la condición más pesada para los demás. De esa unión nace un cuerpo colectivo que Rousseau llama **voluntad general** — no es la suma de las voluntades particulares (eso sería la "voluntad de todos"), sino lo que resulta cuando cada persona piensa en el bien común y no solo en su interés privado.

Un punto que suele aparecer en el comentario es que quien no obedezca la voluntad general "será obligado a ello por todo el cuerpo", lo que Rousseau resume en la paradójica expresión de que se le "forzará a ser libre": la idea es que la verdadera libertad no consiste en hacer lo que a cada uno le apetezca en cada momento, sino en obedecer una ley que uno mismo, como parte del cuerpo político, ha contribuido a crear.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Cada uno de nosotros pone en común su persona y todo su poder bajo la suprema dirección de la voluntad general, y recibimos a cada miembro como parte indivisible del todo."

Identificación: corresponde al momento de la **formación del pacto social** — hay que explicar la enajenación total (cada uno se entrega por entero) y el resultado (un cuerpo colectivo regido por la voluntad general), distinguiendo esto del razonamiento sobre por qué el pacto puede llegar a ser coactivo ("forzar a ser libre"), que es un momento posterior.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 5;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Hume provienen de la *Investigación sobre el entendimiento humano* y giran siempre en torno a su crítica al concepto de **causalidad**. La pregunta es: cuando decimos que A causa B, ¿qué es exactamente lo que percibimos?

Hume observa que lo único que los sentidos nos ofrecen es que B sigue siempre a A (una **conjunción constante** en el tiempo), pero nunca percibimos ningún "vínculo" o "poder" entre ambos que explique por qué A tiene que producir B — no hay ninguna impresión sensible de la "conexión necesaria" misma, solo de una cosa seguida de otra. Su ejemplo típico es el choque de dos bolas de billar: vemos que una golpea a la otra y esta se mueve, pero no vemos ningún "poder" que pase de una bola a la otra, solo la sucesión de los dos hechos.

Entonces, ¿de dónde viene nuestra firme creencia en que A causa B? Para Hume no viene de la razón (que no podría demostrar por qué el futuro tiene que repetir el pasado), sino del **hábito o costumbre**: tras observar muchas veces la misma sucesión, la mente queda acostumbrada a esperar B en cuanto aparece A, y esa expectativa psicológica es lo que llamamos "necesidad" causal — una creencia justificada por la práctica, no un conocimiento racional demostrado.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Tras la repetición de casos similares, la mente es conducida por el hábito a esperar, al aparecer un suceso, su acompañante usual."

Identificación: es el momento central de la crítica humeana — hay que explicar que la "conexión necesaria" no está en los objetos ni se percibe por los sentidos, sino que es un hábito mental generado por la repetición, distinguiéndolo de la mera constatación inicial de que "solo vemos sucesión, no conexión".$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 6;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Habermas provienen de *Tres modelos normativos de democracia* y presentan su comparación entre tres formas de entender la democracia, para terminar defendiendo la suya propia.

El modelo **liberal** entiende la política como un mercado en el que individuos con intereses privados compiten y negocian, y el Estado se limita a arbitrar ese proceso. El modelo **republicano** entiende la democracia como autoorganización política de una comunidad ética que se reconoce a sí misma como un todo mediante la participación de sus ciudadanos — aquí la sociedad se centra en el Estado, no al revés. Habermas no se queda con ninguno de los dos: propone un tercer modelo, la **política deliberativa**, en el que las decisiones legítimas no surgen ni de la negociación de intereses privados (liberal) ni de una identidad ética ya dada (republicano), sino de procesos de comunicación y argumentación pública en condiciones adecuadas.

Para Habermas, lo decisivo es que existan **condiciones de comunicación** suficientemente institucionalizadas —espacios donde los ciudadanos puedan deliberar en igualdad de condiciones— para que la formación de la opinión y la voluntad colectivas tenga fuerza legitimadora. La legitimidad democrática, en su modelo, depende de la **calidad del proceso deliberativo**, no de quién gana una negociación de intereses ni de una supuesta identidad compartida de antemano.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "La democracia equivale a la autoorganización política de la sociedad... la comunidad se torna consciente de sí misma mediante la voluntad colectiva de los ciudadanos."

Identificación: describe el modelo **republicano**, no el deliberativo propio de Habermas — la clave es que la sociedad "se centra en el Estado" y se entiende como una comunidad ética ya constituida, frente al modelo deliberativo, donde la legitimidad depende del proceso comunicativo entre ciudadanos con intereses y valores plurales.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 7;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Ortega y Gasset provienen de *El tema de nuestro tiempo* y desarrollan su teoría del **perspectivismo**: la idea de que todo conocimiento de la realidad se produce desde un punto de vista concreto, y que eso no es un defecto del conocimiento sino su condición.

Ortega parte de una imagen sencilla: dos personas mirando el mismo paisaje desde lugares distintos no ven exactamente lo mismo, pero eso no significa que uno de los dos paisajes sea "falso" — ambos son reales, porque la realidad, como un paisaje, tiene **infinitas perspectivas** igualmente verdaderas, y ninguna por separado agota la realidad entera. Lo que sería falso es pretender que la propia perspectiva es la única válida, ignorando que es solo una entre muchas posibles.

Con esto, Ortega se opone a dos posturas: al **relativismo**, que diría que como cada uno ve algo distinto no hay verdad objetiva (para Ortega sí la hay, pero se construye sumando perspectivas, no eliminándolas); y al **racionalismo abstracto**, que buscaría un "punto de vista absoluto" desde el que ver la realidad sin ningún punto de vista particular, algo que para Ortega es una ficción imposible: todo conocimiento humano es, por naturaleza, conocimiento desde algún lugar.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "El punto de vista absoluto y ubicuo no existe propiamente: es un punto de vista ficticio y abstracto... desde él no se ve lo real."

Identificación: es la crítica de Ortega al **racionalismo abstracto** (el ideal de un conocimiento sin perspectiva), no una defensa del relativismo — hay que aclarar que Ortega no niega que exista una verdad, solo niega que se pueda acceder a ella eliminando todo punto de vista particular.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 8;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Marx provienen de *La ideología alemana* y pueden tratar tres cuestiones distintas, así que lo primero es identificar cuál de ellas plantea el fragmento.

La primera es la **conciencia como producto social**: Marx rechaza que la conciencia sea algo "puro" o independiente de la vida material — nace ligada al lenguaje, y el lenguaje nace de la necesidad de relacionarse con otros seres humanos, así que la conciencia es, desde el principio, un producto social. La segunda es el **Estado y la lucha de clases**: las luchas políticas dentro del Estado son, según Marx, la forma "ilusoria" en que se expresan las luchas reales entre clases sociales — quien controla la producción tiende a presentar su interés de clase como si fuera el interés general de toda la sociedad. La tercera es el **comunismo como movimiento histórico real**: Marx insiste en que el comunismo no es un ideal abstracto al que la realidad deba ajustarse, sino el movimiento efectivo que ya está transformando el "estado de cosas actual", surgido de condiciones materiales concretas.

Las tres ideas comparten el método de Marx, el **materialismo histórico**: explicar las ideas, las instituciones políticas y hasta la conciencia a partir de las condiciones materiales y económicas de una sociedad, y no al revés.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Toda clase que aspire a implantar su dominación tiene que empezar conquistando el poder político, para poder presentar su interés como el interés general."

Identificación: corresponde al análisis del **Estado y la lucha de clases** — hay que explicar que, para Marx, las luchas políticas "visibles" esconden un conflicto de clases más profundo, y que el poder político sirve para universalizar ideológicamente un interés que en realidad es particular.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 9;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Nietzsche provienen de *La gaya ciencia* y suelen tratar una de estas tres cuestiones. La primera es la **crítica a la moral tradicional**: Nietzsche denuncia que, hasta ahora, nadie ha tratado la moral como un verdadero problema filosófico — al contrario, ha funcionado como un lugar de acuerdo pacífico donde los pensadores dejaban de discutir, en vez de someterla ella misma a examen crítico.

La segunda es la **muerte de Dios y el nihilismo**: Nietzsche anuncia que la creencia en el Dios cristiano ha dejado de ser creíble para la cultura europea, y que este acontecimiento va a proyectar "sombras" sobre toda la civilización — porque buena parte de los valores y certezas de Occidente dependían de esa creencia; al desaparecer, se abre el riesgo del **nihilismo** (la sensación de que nada tiene ya un valor firme).

La tercera es la **crítica a las convicciones en la ciencia**: Nietzsche sostiene que una convicción (una creencia sostenida con firmeza, casi como un dogma) no debería tener cabida en el conocimiento científico salvo que se rebaje a ser una simple hipótesis provisional sometida a prueba — la ciencia, para ser honesta, tiene que desconfiar de sus propias certezas, no aferrarse a ellas.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "El mayor acontecimiento reciente es que Dios ha muerto, y esto empieza ya a proyectar sus primeras sombras sobre Europa."

Identificación: corresponde a la **muerte de Dios y el nihilismo** — conviene explicar que "Dios ha muerto" no es un enunciado sobre biología o teología, sino sobre la pérdida de credibilidad cultural de la creencia cristiana, y anticipar las consecuencias (pérdida de certezas, riesgo de nihilismo) que Nietzsche desarrolla en el resto del texto.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 10;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, los textos de Aristóteles provienen de la *Ética a Nicómaco* y tratan dos cuestiones relacionadas: qué es la **felicidad** (el fin último de la vida humana) y cómo se adquiere la **virtud**.

Sobre la felicidad, Aristóteles descarta que consista en el placer o la diversión —sería absurdo vivir y esforzarse toda la vida solo para divertirse, aunque reconoce que la diversión tiene su lugar como descanso necesario para poder dedicarse después a cosas serias—. Lo característico de la felicidad es que es el único fin que se busca **por sí mismo** y nunca como medio para otra cosa: todo lo demás (dinero, honores, placer) se desea en vista de algo más, pero la felicidad se desea solo por ella misma. Entre las actividades humanas, Aristóteles sitúa en el punto más alto la **actividad contemplativa** (el ejercicio de la razón teórica), porque no depende de fines externos ni de la agitación de la acción política o militar, y lleva consigo un placer propio.

Sobre la virtud, Aristóteles insiste en que no basta con conocer la teoría de lo que está bien: **nos volvemos justos haciendo actos justos**, igual que se aprende un oficio practicándolo — quien se refugia solo en la teoría, sin actuar, cree que filosofa pero en realidad no se hace mejor persona.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Nadie podría llegar a ser bueno sin realizar acciones justas y moderadas; pero la mayoría de la gente, refugiándose en la teoría, cree filosofar y así poder ser buena."

Identificación: corresponde al tema de la **virtud como hábito práctico**, no a la definición de la felicidad — el argumento central es que la virtud se adquiere actuando, no solo conociendo la teoría moral, y hay que señalar la crítica implícita a quienes confunden "saber de ética" con "ser éticos".$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 11;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, el único texto disponible de Agustín de Hipona proviene de *Del libre albedrío*, pero conviene prepararlo con el mismo cuidado que a los autores con más ejercicios, porque cualquier convocatoria puede incluirlo y su argumento tiene una estructura muy concreta que hay que dominar.

El problema de fondo es: si Dios es justo y castiga el pecado y premia las buenas acciones, ¿qué exige eso sobre la naturaleza humana? Agustín argumenta que el castigo y el premio solo tienen sentido si las acciones que se castigan o premian fueron hechas **libremente** — un acto que no se hace voluntariamente no puede llamarse propiamente ni pecado ni buena acción, porque falta la responsabilidad de quien actúa. Por tanto, si el ser humano no tuviera **libre albedrío** (voluntad libre para elegir entre el bien y el mal), sería injusto tanto castigarlo como premiarlo por sus actos.

El argumento tiene una estructura muy clara que conviene identificar en el comentario: parte de un hecho que se da por bueno (que existe la justicia divina, que premia y castiga) y de ahí **deduce** una condición necesaria para que ese hecho tenga sentido (que el ser humano sea libre). Es un argumento típico de la filosofía cristiana medieval: no se limita a describir la libertad humana, sino que la demuestra a partir de una verdad religiosa que se da por establecida.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "Si el ser humano no tuviera una voluntad libre, tanto el castigo como el premio serían injustos; pero ha tenido que haber justicia en ambos, luego el ser humano tiene libre albedrío."

Identificación: es el argumento central de Agustín sobre el **libre albedrío** — en el comentario conviene explicitar la forma del razonamiento (si no hay libertad, no hay justicia posible en el castigo/premio; hay justicia; luego hay libertad) y situarlo en su contexto: es una prueba teológica de una tesis antropológica.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 12;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$En el banco PAU Madrid actualmente incluido en Kairo, el único texto disponible de Hannah Arendt proviene de *La condición humana*, y al igual que con Agustín de Hipona conviene prepararlo con la misma solidez que a los autores más representados, porque puede aparecer en cualquier convocatoria.

Arendt analiza cómo la tradición filosófica occidental, desde la Antigüedad y reforzada después por el cristianismo, ha entendido siempre la **vita activa** (la vida dedicada a la acción, el trabajo y la participación en los asuntos humanos) como algo de valor **derivado y secundario**, cuyo sentido consistiría solo en servir a las necesidades de la **vita contemplativa** (la vida dedicada a la contemplación y el pensamiento, considerada la más elevada). El cristianismo, con su promesa de una vida contemplativa plena en el más allá, reforzó todavía más esta jerarquía: la acción en este mundo quedaría subordinada a la contemplación como preparación para una vida futura.

Arendt no se limita a describir esta jerarquía tradicional: la presenta como una decisión filosófica e histórica concreta, no como algo evidente por sí mismo, abriendo la puerta a preguntarse si la vida activa merece de verdad ese lugar secundario — una pregunta que desarrolla en el resto de *La condición humana*, aunque el fragmento de examen se limite a exponer cómo se formó esa jerarquía tradicional.$mkd$, worked_example_markdown = $mkd$Ejemplo didáctico (parafraseado): "La vita activa recibe su significado y su limitada dignidad de la vita contemplativa, a cuyas necesidades sirve; el cristianismo reforzó esta subordinación con su promesa de una vida futura dedicada a la contemplación."

Identificación: describe la **jerarquía tradicional entre vita activa y vita contemplativa** — en el comentario conviene explicar los dos términos y señalar el papel histórico que Arendt atribuye al cristianismo en consolidar esa jerarquía, sin perder de vista que Arendt la describe para después cuestionarla.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 13;

UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Cuando el examen pide "exponga el problema de la ética y/o moral en un autor o corriente filosófica de la época [antigua/medieval/moderna/contemporánea]", el enunciado normalmente fija también una época — no basta con elegir el autor que mejor domines, primero hay que comprobar si tu autor pertenece a la época pedida.

De los tres autores del temario de Madrid que tratan la ética, cada uno pertenece a una época distinta: **Aristóteles** (época antigua) entiende la ética como la búsqueda de la felicidad a través de la virtud, que se adquiere practicando buenas acciones, no solo conociendo la teoría moral. **Agustín de Hipona** (época medieval) aborda la moral desde una perspectiva religiosa, vinculando la posibilidad del bien y del mal a la existencia del libre albedrío. **Nietzsche** (época contemporánea) no propone una ética positiva sino una crítica radical a la moral tradicional: denuncia que la moral nunca ha sido tratada como un problema real.

Estrategia de respuesta: (1) el problema ya lo tienes (ética y/o moral); (2) identifica la época que pide el enunciado; (3) si es antigua, desarrolla Aristóteles; si es medieval, Agustín de Hipona; si es contemporánea, Nietzsche. **Si te piden época moderna, ninguno de estos tres autores encaja** — tendrás que apoyarte en lo que hayas visto en clase sobre ética moderna, porque el banco disponible aquí no cubre todavía esa combinación.$mkd$, worked_example_markdown = $mkd$Ejemplo de elección razonada: si el enunciado pide "el problema de la ética y/o moral en un autor o corriente de la época contemporánea", no puedes usar Aristóteles (antigua) ni Agustín de Hipona (medieval) aunque los domines mejor — la época exigida solo deja Nietzsche como opción válida entre estos tres.$mkd$, practice_prompt = $mkd$El enunciado pide: "Exponga el problema de la ética y/o moral en un autor o corriente filosófica de la época antigua." De los tres autores del temario que tratan la ética (Aristóteles, Agustín de Hipona, Nietzsche), ¿cuál es el único válido para esta época? Redacta en 8-10 líneas su postura central.$mkd$, alert_markdown = NULL WHERE subject = 'historia_filosofia' AND sort_order = 14;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Cuando el examen pide "exponga el problema de la sociedad y/o la política en un autor o corriente filosófica de la época [X]", primero hay que comprobar la época exigida — no basta con elegir el autor que mejor domines.

De los tres autores del temario de Madrid que tratan este problema: **Rousseau** (época moderna) aborda el problema desde el contractualismo: explica cómo los seres humanos pasan del estado de naturaleza a la sociedad civil mediante un pacto que da lugar a la voluntad general. **Marx** y **Habermas** pertenecen ambos a la época contemporánea: Marx analiza la sociedad y el Estado desde el materialismo histórico (las luchas políticas expresan conflictos de clase); Habermas compara modelos de democracia y defiende que la legitimidad depende de la calidad de los procesos de comunicación pública.

Estrategia: si la época pedida es moderna, la única opción de este roster es Rousseau. Si es contemporánea, puedes elegir entre Marx o Habermas — el que mejor controles. **Si te piden época antigua o medieval, ninguno de estos tres autores encaja**: tendrás que recurrir a lo visto en clase, porque el banco disponible aquí no cubre todavía esas combinaciones.$mkd$, worked_example_markdown = $mkd$Ejemplo de elección razonada: si el enunciado pide "la época contemporánea", tanto Marx como Habermas son válidos — elige el que recuerdes con más seguridad (por ejemplo, si controlas bien la distinción entre los tres modelos de democracia de Habermas, esa es tu opción más eficaz).$mkd$, practice_prompt = $mkd$El enunciado pide: "Exponga el problema de la sociedad y/o la política en un autor o corriente filosófica de la época moderna." De los tres autores del temario que tratan este problema (Rousseau, Marx, Habermas), ¿cuál es el único válido para esta época? Redacta en 8-10 líneas su tesis central.$mkd$, alert_markdown = NULL WHERE subject = 'historia_filosofia' AND sort_order = 15;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Cuando el examen pide "exponga el problema del ser humano en un autor o corriente filosófica de la época [X]", primero hay que comprobar la época exigida.

De los cuatro autores del temario de Madrid que tratan este problema: **Platón** (época antigua) define al ser humano a partir del dualismo entre alma y cuerpo — para él, lo propiamente humano es el alma, mientras que el cuerpo es más bien un obstáculo del que debe liberarse para conocer de verdad. **Agustín de Hipona** (época medieval) sitúa lo definitorio del ser humano en el libre albedrío. **Marx** y **Hannah Arendt** pertenecen ambos a la época contemporánea: Marx entiende al ser humano como un ser esencialmente social (ni siquiera la conciencia existe al margen de las relaciones sociales); Arendt analiza cómo la tradición ha jerarquizado la vita activa y la vita contemplativa.

Estrategia: si la época es antigua, Platón; si es medieval, Agustín de Hipona; si es contemporánea, Marx o Arendt (el que mejor controles). **Si te piden época moderna, ninguno de estos cuatro autores encaja**: tendrás que apoyarte en lo visto en clase, porque el banco disponible aquí no cubre todavía esa combinación.$mkd$, worked_example_markdown = $mkd$Ejemplo de elección razonada: si el enunciado pide "época antigua", la única opción válida de este roster es Platón — no importa si controlas mejor a Marx o Arendt, porque no pertenecen a esa época.$mkd$, practice_prompt = $mkd$El enunciado pide: "Exponga el problema del ser humano en un autor o corriente filosófica de la época medieval." De los cuatro autores del temario que tratan este problema (Platón, Agustín de Hipona, Marx, Hannah Arendt), ¿cuál es el único válido para esta época? Redacta en 8-10 líneas cómo define ese autor lo propiamente humano.$mkd$, alert_markdown = NULL WHERE subject = 'historia_filosofia' AND sort_order = 16;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Cuando el examen pide "exponga el problema de Dios en un autor o corriente filosófica de la época [X]", primero hay que comprobar la época exigida — los tres autores del temario que tratan este problema pertenecen, convenientemente, a tres épocas distintas.

**Tomás de Aquino** (época medieval) parte de la observación del mundo sensible: sus cinco vías arrancan de hechos como el movimiento, la causalidad o el orden finalista, y concluyen que tiene que existir un primer término que explique esa cadena. **Descartes** (época moderna) prueba la existencia de Dios desde dentro de la propia mente, a partir de la idea de infinito que tiene en sí. **Nietzsche** (época contemporánea) no discute pruebas racionales: anuncia que la creencia cristiana en Dios ha perdido credibilidad cultural, un diagnóstico sobre las consecuencias de esa pérdida de fe, no un argumento sobre si Dios existe.

Estrategia: si la época es medieval, Tomás de Aquino; si es moderna, Descartes; si es contemporánea, Nietzsche (dejando claro que su postura es un diagnóstico cultural, no una prueba a favor o en contra). **Si te piden época antigua, ninguno de estos tres autores encaja**: tendrás que recurrir a lo visto en clase, porque el banco disponible aquí no cubre todavía esa combinación.$mkd$, worked_example_markdown = $mkd$Ejemplo de elección razonada: si el enunciado pide "la época contemporánea", la única opción válida es Nietzsche — pero recuerda dejar explícito en la respuesta que su argumento no es una prueba racional como las de Descartes o Tomás de Aquino, sino un diagnóstico cultural.$mkd$, practice_prompt = $mkd$El enunciado pide: "Exponga el problema de Dios en un autor o corriente filosófica de la época moderna." De los tres autores del temario que tratan este problema (Tomás de Aquino, Descartes, Nietzsche), ¿cuál es el único válido para esta época? Redacta en 8-10 líneas su postura, dejando claro si es una prueba a favor de la existencia de Dios o un diagnóstico sobre la pérdida de esa creencia.$mkd$, alert_markdown = $mkd$⚠️ No trates la postura de Nietzsche como si fuera "una prueba más" de que Dios no existe — su argumento es de otro tipo (cultural e histórico), y tratarlo como si compitiera directamente con las pruebas racionales de Descartes o Tomás de Aquino es un error habitual.$mkd$ WHERE subject = 'historia_filosofia' AND sort_order = 17;
UPDATE curriculum_content_v2 SET concept_markdown = $mkd$Cuando el examen pide "exponga el problema del conocimiento y/o la realidad en un autor o corriente filosófica de la época [X]", primero hay que comprobar la época — este es el problema con más autores del temario (cinco), pero tres de ellos pertenecen a la misma época.

**Platón** (época antigua) sostiene que conocer es en realidad recordar: el alma tuvo contacto con las Ideas eternas antes de nacer. **Descartes**, **Hume** y **Kant** pertenecen los tres a la época moderna, con posturas distintas entre sí: Descartes busca una base racional segura (el cogito); Hume defiende que todo conocimiento procede de la experiencia sensible y critica la causalidad; Kant intenta superar el enfrentamiento entre ambos con los juicios sintéticos a priori. **Ortega y Gasset** (época contemporánea) defiende el perspectivismo: todo conocimiento se produce desde un punto de vista concreto.

Estrategia: si la época es antigua, Platón; si es moderna, elige entre Descartes, Hume o Kant (el que mejor controles — son posturas distintas entre sí, así que no los mezcles en la misma respuesta); si es contemporánea, Ortega y Gasset. **Si te piden época medieval, ninguno de estos cinco autores encaja**: tendrás que apoyarte en lo visto en clase, porque el banco disponible aquí no cubre todavía esa combinación.$mkd$, worked_example_markdown = $mkd$Ejemplo de elección razonada: si el enunciado pide "época moderna" y controlas bien la distinción entre juicios analíticos/sintéticos y a priori/a posteriori, Kant es una opción sólida — pero Descartes o Hume son igual de válidos para esa época si los conoces mejor; lo importante es no mezclar los tres en la misma respuesta.$mkd$, practice_prompt = $mkd$El enunciado pide: "Exponga el problema del conocimiento y/o la realidad en un autor o corriente filosófica de la época antigua." De los cinco autores del temario que tratan este problema (Platón, Descartes, Hume, Kant, Ortega y Gasset), ¿cuál es el único válido para esta época? Redacta en 8-10 líneas su postura central.$mkd$, alert_markdown = NULL WHERE subject = 'historia_filosofia' AND sort_order = 18;
